const LEDE = "<b>당하는 건 1화와 10화, 딱 두 번뿐입니다.</b> 20년을 형제로 산 형에게 회사를 통째로 빼앗기고 1998년으로 돌아간다. 형의 종잣돈을 끊고, 형이 접근할 여자의 집을 먼저 살리고, 형의 특허를 먼저 내고, 형 옆에 내 사람을 심는다. 전생에 나를 밟은 순서대로 하나씩 뒤집는다. 그런데 8화 끝에서 형이 귀에 대고 묻는다. <b>“너 2020년 3월 알지?”</b> 그림은 전부 게임에 이미 있는 에셋이며, 새로 생성한 이미지는 하나도 없습니다.";

const EPISODES = [
  {
    no: "1화",
    title: "오늘부터 네 형이다",
    log: "열두 살에 우리 집에 와 20년을 형제로 산 사람. 어머니가 아들처럼 키웠고, 지분 40%를 계약서도 없이 준 사람. 그 형이 내 여자친구와 짜고 회사를 삼킨다.",
    cuts: [
      ["assets/mc-38-lux-03.png", "2026년. 서른여덟.<br>회사 지분 60%, 가을엔 상장이었다.<br>나는 다 가진 줄 알았다."],
      ["assets/situ/guy-08-date.webp", "그 사람은 내 <b>형</b>이었다.<br>피는 안 섞였지만, 그렇게 불렀다."],
      ["assets/situ/guy-08-travel.webp", "열두 살 때 우리 집에 왔다.<br>아버지 친구의 아들이었는데,<br>그 집이 부도가 났다."],
      ["assets/mc-boy.webp", "장례식 다음 날 어머니가 데려왔다.<br>“오늘부터 네 형이다.”"],
      ["assets/mc-teen.webp", "우리는 한 방을 썼다.<br>이층침대 위아래로 <b>20년</b>을 잤다."],
      ["assets/mc-young.webp", "형은 어머니를 어머니라고 불렀다.<br>나보다 살가웠다.<br>어머니도 형을 더 예뻐했다."],
      ["assets/situ/guy-08-night-2.webp", "회사도 같이 차렸다.<br>내가 지분 <b>40%</b>를 그냥 줬다.<br>계약서도 안 썼다. 형인데."],
      ["assets/situ/guy-08-wed.webp", "내 결혼식 사회도<br>형이 보기로 돼 있었다."],
      ["assets/situ/heroine-gift.webp", "여자친구와는 그해 10월에 식을 올리기로 했다.<br>예물도 신혼집도 이미 내 이름으로 끝내놨다."],
      ["assets/situ/heroine-night-2.webp", "두 달 전 그 여자가<br>아이가 생긴 것 같다고 했다.<br>나는 그날 바로 식장을 잡았다.", "shock", "아이"],
      ["assets/mc-38-lux-02.png", "상장 실사 서류가 산더미였다.<br>인감은 침대 옆 서랍에 뒀다.<br>매번 금고를 여는 게 귀찮았다."],
      ["assets/situ/guy-08-gift.webp", "“내가 다 처리할게.<br>넌 실사만 신경 써.”<br>형이 그렇게 말했다.", "q"],
      ["assets/mc-male.webp", "나는 고맙다고 했다.<br>그게 마지막 실수였다."],
      ["assets/int-betrayal.webp", "6월 12일. 등기가 바뀌어 있었다.<br>지분 60%가 하룻밤 사이<br>통째로 넘어가 있었다.", "shock", "배신"],
      ["assets/int-betrayal-2.webp", "위조 계약서. 날짜는 석 달 전.<br>내가 형 생일상을 차려주던<br>바로 그 주였다.", "shock", "석 달 전"],
      ["assets/mc-38-lux-04.png", "그런데 인감은—<br>위조가 아니었다. <b>진짜 내 인감</b>이었다."],
      ["assets/situ/heroine-night-3.webp", "그 서랍을 아는 사람은 셋.<br>나, 그 여자, 그리고 <b>형</b>."],
      ["assets/situ/guy-08-sad.webp", "3년 전부터였다.<br>내가 무릎 꿇고 청혼하던 그날에도<br>둘은 만나고 있었다.", "shock", "3년"],
      ["assets/night/heroine.png", "“임신은 거짓말 아니야.<br>근데— <b>네 아이가 아니야.</b>”", "shock", "아이"],
      ["assets/int-betrayal-3.webp", "그날 형은 회사 전체에 메일을 돌렸다.<br>‘대표가 회삿돈을 들고 잠적했습니다.’<br>그리고 <b>어머니한테도</b> 똑같이 말했다.", "next", "NEXT"],
    ],
  },
  {
    no: "2화",
    title: "도장이 안 맞는대",
    log: "옥상에서 떨어지려던 순간 1998년으로 돌아간다. 형은 아직 우리 집에 오기 전이다. 나는 형을 막지 않는다. 대신 형의 첫 종잣돈을 끊는다.",
    cuts: [
      ["assets/int-rooftop.webp", "7월. 빚 17억.<br>옥상 난간 위로 비가 내렸다."],
      ["assets/int-flash.webp", "“딱 한 번만… 다시 살 수 있다면.”<br>시간이 <b>거꾸로</b> 쏟아졌다."],
      ["assets/int-wake.webp", "눈을 떴다."],
      ["assets/mc-10.webp", "거울 속엔 <b>열 살의 내가</b> 있었다.", "shock", "회귀"],
      ["assets/mc-11.webp", "1998년 3월. IMF의 겨울.<br>전 재산은 용돈 3만원."],
      ["assets/int-resolve.webp", "삼성전자 900원.<br>나는 앞으로 <b>28년</b>을 안다.", "gold", "기억"],
      ["assets/mc-12.webp", "그런데 달력을 보고 손이 떨렸다."],
      ["assets/situ/guy-08-night-4.webp", "형이 우리 집에 오기<br><b>두 달 전</b>이었다.", "shock", "두 달"],
      ["assets/mc-13.webp", "막을 수 있었다.<br>어머니한테 한마디만 하면 됐다."],
      ["assets/mc-14.webp", "그런데 막지 않았다."],
      ["assets/mc-15.webp", "형이 오는 걸 막는 게 아니라—<br>형이 <b>뭘 훔칠지</b>를 나는 안다.", "gold", "설계"],
      ["assets/int-resolve-2.webp", "전생에 형은 스물넷에<br>우리 집을 담보로 5천만원을 빌렸다.<br>그게 형의 첫 종잣돈이었다."],
      ["assets/situ/guy-08-night-3.webp", "어머니 도장을 몰래 들고 나가서."],
      ["assets/mc-16.webp", "나는 열여덟에 그 도장을 바꿔놨다.<br>어머니는 눈치도 못 챘다."],
      ["assets/mc-17.webp", "2010년. 형이 은행에서 돌아왔다.<br>빈손으로.", "win", "1차 저지"],
      ["assets/situ/guy-08-night.webp", "“이상하네. 도장이 안 맞는대.”", "q"],
      ["assets/mc-18.webp", "나는 그 5천만원을<br>내 이름으로 빌렸다."],
      ["assets/mc-19.webp", "그리고 그 돈으로<br>삼성전자를 샀다.", "win", "종잣돈"],
      ["assets/mc-20.webp", "형의 첫 판은<br>시작도 못 하고 끝났다."],
      ["assets/situ/heroine-date.webp", "다음 표적은—<br>그 여자의 집이다.", "next", "NEXT"],
    ],
  },
  {
    no: "3화",
    title: "내가 먼저 살렸다",
    log: "전생에 형은 그 여자 아버지 회사가 부도난 틈에 접근했다. 그래서 나는 그 회사를 먼저 살린다. 형이 들어갈 문을 막아버린 것이다.",
    cuts: [
      ["assets/situ/heroine-sad.webp", "전생에 그 여자는<br>2003년에 형을 만났다."],
      ["assets/situ/girl-05-sad.webp", "카드대란으로<br>아버지 회사가 부도났을 때였다."],
      ["assets/situ/guy-08-travel.webp", "형이 그때 나타나<br>빚을 갚아줬다."],
      ["assets/mc-21.webp", "그 여자가 형한테 못 벗어난 이유가<br>거기 있었다."],
      ["assets/mc-22.webp", "그럼 <b>부도를 안 나게</b> 하면 된다.", "gold", "발상"],
      ["assets/situ/guy-01-date.webp", "회계사 하나를 찾아갔다.<br>아직 무명이었다."],
      ["assets/mc-23.webp", "전생에 이 사람은<br>내 회사 재무이사가 된다.<br>그리고 나를 무너뜨린다."],
      ["assets/situ/guy-01-gift.webp", "“지금 연봉의 세 배를 드리겠습니다.”"],
      ["assets/mc-24.webp", "적을 먼저 사면<br>적이 아니게 된다.", "gold", "선점"],
      ["assets/situ/guy-01-travel.webp", "그 사람이 장부를 봤다.<br>“살릴 수 있습니다. 지금이면.”"],
      ["assets/mc-25.webp", "2003년 2월.<br>부도 나흘 전에 자금을 넣었다."],
      ["assets/situ/girl-06-gift.webp", "회사가 살았다.<br>직원 서른 명이 그대로 남았다.", "win", "인수"],
      ["assets/situ/heroine-gift.webp", "그 여자 아버지가 나를 불렀다.<br>“자네가 아니었으면 우린 끝이었네.”"],
      ["assets/situ/guy-08-sad.webp", "그해 겨울, 형이 그 집 앞을 서성였다.<br>갚아줄 빚이 없었다.", "win", "문 차단"],
      ["assets/mc-26.webp", "형은 그 여자 이름도 모르고 지나갔다."],
      ["assets/situ/heroine-travel.webp", "그 여자는 나중에<br>평범한 사람과 결혼했다."],
      ["assets/mc-27.webp", "전생에 나를 배신한 사람 하나가<br>이번 생엔 그냥 <b>모르는 사람</b>이 됐다."],
      ["assets/situ/girl-07-gift.webp", "복수는 되갚는 게 아니라<br><b>안 만나는 것</b>일 수도 있다.", "gold", "방식"],
      ["assets/mc-28.webp", "두 개를 끊었다.<br>돈과 여자."],
      ["assets/situ/guy-01-sad.webp", "다음은—<br>형 옆에 심을 사람이다.", "next", "NEXT"],
    ],
  },
  {
    no: "4화",
    title: "형 옆에 내 사람을 심었다",
    log: "전생에 나를 무너뜨린 재무이사. 이번엔 내가 먼저 고용해 형 회사로 보낸다. 12년 뒤 이 한 수가 나를 살린다.",
    cuts: [
      ["assets/situ/guy-01-night.webp", "2005년. 형이 작은 회사를 차렸다."],
      ["assets/mc-29.webp", "전생보다 5년 늦은 출발이었다.<br>종잣돈을 내가 끊었으니까."],
      ["assets/situ/guy-01-wed.webp", "나는 그 회계사를 불렀다."],
      ["assets/mc-30.webp", "“우리 형 회사에 들어가 주세요.<br>월급은 제가 드립니다.”", "q"],
      ["assets/situ/guy-02-date.webp", "“왜 그런 일을 시키십니까.”"],
      ["assets/mc-31.webp", "“언젠가 형이 저를 죽이려 할 겁니다.<br>그때 딱 한 번만 제 편을 들어주세요.”", "q"],
      ["assets/situ/guy-02-gift.webp", "그 사람은 오래 생각하더니<br>고개를 끄덕였다."],
      ["assets/situ/guy-08-gift.webp", "형은 그를 반겼다.<br>싸고 유능했으니까."],
      ["assets/mc-32.webp", "형은 몰랐다.<br>그 사람 통장에 매달<br>내 돈이 들어간다는 걸.", "gold", "심기"],
      ["assets/situ/guy-02-travel.webp", "그때부터 나는<br>형의 모든 계약서를 봤다."],
      ["assets/situ/guy-02-night.webp", "형이 누구를 만나는지,<br>어디에 돈을 넣는지."],
      ["assets/mc-33.webp", "전생엔 내가 발가벗겨졌다.<br>이번엔 형이 그렇다.", "win", "정보 역전"],
      ["assets/situ/guy-03-date.webp", "2007년 8월.<br>형이 대출을 최대로 당겼다."],
      ["assets/mc-34.webp", "나는 그 한 달 뒤를 안다."],
      ["assets/situ/guy-03-gift.webp", "2008년 9월. 리먼이 무너졌다."],
      ["assets/situ/guy-03-sad.webp", "형은 반토막 난 자산에<br>이자만 남았다.", "win", "2차"],
      ["assets/mc-35.webp", "나는 8월에 전부 팔았고<br>2009년 3월에 전부 샀다."],
      ["assets/mc-36.webp", "같은 2년을 지나<br>형은 빚이, 나는 자산이 됐다."],
      ["assets/situ/guy-04-date.webp", "형이 처음으로 나에게 전화를 걸었다."],
      ["assets/situ/guy-04-gift.webp", "“…돈 좀 빌려줄 수 있냐.”", "next", "NEXT"],
    ],
  },
  {
    no: "5화",
    title: "네 아이템은 내가 먼저 냈다",
    log: "형이 재기하려고 꺼낸 아이템. 전생에 그걸로 큰 회사가 됐다. 나는 특허를 먼저 내고, 형이 그걸 알게 만든다.",
    cuts: [
      ["assets/situ/guy-04-night.webp", "형이 재기하려고 아이템 하나를 꺼냈다."],
      ["assets/mc-37.webp", "나는 그게 뭔지 안다.<br>전생에 그걸로<br>내 회사를 삼켰으니까."],
      ["assets/situ/guy-05-date.webp", "형이 특허를 내러 갔다."],
      ["assets/situ/guy-05-gift.webp", "이미 등록돼 있었다.<br><b>3년 전에.</b>", "shock", "선등록"],
      ["assets/mc-38.webp", "출원인 이름을 보고<br>형이 한참을 서 있었다고 한다."],
      ["assets/mc-38-lux-01.png", "내 이름이었다.", "win", "특허"],
      ["assets/situ/guy-05-night.webp", "형이 찾아왔다.<br>20년 만에 처음으로 화를 냈다."],
      ["assets/situ/guy-06-date.webp", "“너 나한테 왜 이래.”", "q"],
      ["assets/mc-38-lux-02.png", "나는 대답하지 않았다.<br>말해도 못 알아들을 테니까."],
      ["assets/situ/guy-06-gift.webp", "“형이 나한테 뭘 했는지<br>형은 아직 모르지.”", "q"],
      ["assets/mc-38-lux-04.png", "형이 이해 못 하는 얼굴로 돌아갔다."],
      ["assets/situ/guy-06-night.webp", "그 아이템은 내가 사업화했다."],
      ["assets/mc-38-lux-05.png", "2011년. 매출 300억.", "win", "300억"],
      ["assets/situ/guy-07-date.webp", "형은 그 회사 협력업체로 들어왔다."],
      ["assets/mc-38-lux-06.png", "내 결재판에 형 이름이 올라왔다."],
      ["assets/situ/guy-07-gift.webp", "나는 도장을 찍었다.<br>단가는 깎지 않았다."],
      ["assets/mc-38-lux-07.png", "망하게 두면 재미가 없다.<br><b>내 밑에 있어야</b> 재미있다.", "gold", "악취미"],
      ["assets/situ/guy-07-night.webp", "형은 그걸 은혜라고 생각했다."],
      ["assets/mc-38-lux-08.png", "전생에 내가 형한테 그랬던 것처럼."],
      ["assets/night/girl-heiress.png", "그 무렵, 한 그룹에서 연락이 왔다.", "next", "NEXT"],
    ],
  },
  {
    no: "6화",
    title: "리먼 때 사둔 지분",
    log: "전생에 내 회사를 최종적으로 삼킨 그룹. 아직은 중견기업이다. 나는 리먼 때 이미 지분을 모아뒀다.",
    cuts: [
      ["assets/situ/girl-heiress-date.webp", "협상 자리에 그 집 딸이 나왔다.<br>스물여섯. 후계자 수업 중이라고 했다."],
      ["assets/mc-38-lux-09.png", "전생에 이 집안이<br>내 회사를 최종적으로 삼켰다."],
      ["assets/situ/girl-heiress-gift.webp", "“저희와 합병하시죠.<br>조건은 저희가 맞추겠습니다.”", "q"],
      ["assets/mc-38-lux-10.png", "나는 서류를 펴지 않았다."],
      ["assets/situ/guy-08-night-2.webp", "대신 다른 서류를 내밀었다."],
      ["assets/mc-26.webp", "2008년 10월,<br>그 집 계열사가 바닥일 때<br>내가 사둔 지분이었다.", "gold", "매집"],
      ["assets/situ/girl-heiress-travel.webp", "“17%요.<br>2대 주주가 접니다.”", "shock", "17%"],
      ["assets/situ/guy-heir-date.webp", "그 집안 회장이 직접 나왔다."],
      ["assets/situ/guy-heir-gift.webp", "“자네, 그때 왜 그걸 샀나.<br>다들 팔던 때인데.”", "q"],
      ["assets/mc-27.webp", "“쌌으니까요.”"],
      ["assets/situ/guy-heir-travel.webp", "회장이 웃었다.<br>웃으면서 손이 떨리는 걸 봤다."],
      ["assets/mc-28.webp", "합병은 없던 일이 됐다."],
      ["assets/situ/guy-heir-sad.webp", "대신 그 집안이<br>내 계열사가 됐다.", "win", "경영권"],
      ["assets/situ/girl-heiress-night.webp", "그 집 딸이 내 밑에서 일하게 됐다."],
      ["assets/mc-29.webp", "전생에 나를 밟은 순서대로<br>하나씩 뒤집는 중이었다."],
      ["assets/situ/girl-heiress-night-2.webp", "“오빠는 어떻게<br>다 알고 있는 것처럼 굴어요?”", "q"],
      ["assets/mc-30.webp", "나는 웃고 말았다."],
      ["assets/situ/girl-heiress-sad.webp", "그때 그 여자 눈빛을<br>나는 대수롭지 않게 넘겼다.", "shock", "복선"],
      ["assets/mc-31.webp", "그게 실수였다."],
      ["assets/situ/guy-08-date.webp", "2013년. 형이 나를 보자고 했다.", "next", "NEXT"],
    ],
  },
  {
    no: "7화",
    title: "형이 무릎을 꿇었다",
    log: "20년을 형제로 산 사람이 내 앞에 앉아 투자를 부탁한다. 전생에 내가 형에게 지분 40%를 그냥 줬던 그 자리에서.",
    cuts: [
      ["assets/situ/guy-08-date.webp", "형이 나를 보자고 했다.<br>회사 근처 국밥집이었다."],
      ["assets/mc-32.webp", "전생에 우리가 창업을 결심한<br>바로 그 집이었다."],
      ["assets/situ/guy-08-gift.webp", "형이 봉투를 내밀었다.<br>사업계획서였다."],
      ["assets/situ/guy-08-travel.webp", "“10억만 넣어줘.<br>지분은 네가 60 가져가.”", "q"],
      ["assets/mc-33.webp", "전생에 내가 형한테 했던 말이었다.<br>비율만 반대였다.", "shock", "데자뷔"],
      ["assets/situ/guy-08-sad.webp", "“우리 사이에 계약서가 필요하냐.”<br>형이 그렇게 말했다."],
      ["assets/mc-34.webp", "나는 계약서를 꺼냈다.<br>서른두 장짜리였다."],
      ["assets/situ/guy-01-date.webp", "옆에는 그 회계사가 앉아 있었다."],
      ["assets/situ/guy-01-gift.webp", "형은 아직도<br>그 사람이 내 사람인 걸 몰랐다.", "gold", "아직 모른다"],
      ["assets/mc-35.webp", "“읽고 서명해. 한 줄도 빼지 말고.”"],
      ["assets/situ/guy-08-night.webp", "형 얼굴이 하얘졌다.<br>연대보증 조항 때문이었다."],
      ["assets/mc-36.webp", "전생에 내가 형한테 없이 준 그것을,<br>이번엔 형이 목숨 걸고 받아야 했다."],
      ["assets/situ/guy-08-night-2.webp", "형이 펜을 들었다 놨다 했다."],
      ["assets/mc-37.webp", "한 시간이 걸렸다."],
      ["assets/situ/guy-08-night-3.webp", "결국 서명했다.", "win", "서명"],
      ["assets/mc-38.webp", "국밥은 식어 있었다."],
      ["assets/situ/guy-08-wed.webp", "일어서면서 형이 말했다.<br>“고맙다. 역시 형제밖에 없다.”", "q"],
      ["assets/mc-38-lux-01.png", "그 말을 듣고<br>처음으로 속이 시원하지 않았다."],
      ["assets/mc-38-lux-02.png", "이겼는데 왜 이러지, 싶었다."],
      ["assets/situ/guy-08-night-4.webp", "그때 형이 뒤돌아보며 웃었다.", "next", "NEXT"],
    ],
  },
  {
    no: "8화",
    title: "이 나라에서 제일 어린 부자",
    log: "2013년. 스물다섯에 자산 1조. 형은 내 협력업체 사장이고, 나를 배신했던 사람들은 전부 내 밑에 있다. 완벽했다.",
    cuts: [
      ["assets/mc-38-lux-03.png", "2013년. 스물다섯."],
      ["assets/mc-38-lux-04.png", "자산 <b>1조</b>.<br>이 나라에서 제일 어린 부자가 됐다.", "win", "1조"],
      ["assets/situ/girl-08-gift.webp", "기사에 내 얼굴이 났다.<br>모자이크 없이."],
      ["assets/mc-38-lux-05.png", "전생에 횡령 의혹으로 났던<br>그 신문사였다."],
      ["assets/situ/guy-heir-night.webp", "그 집안 회장이 내 밑에 있었다."],
      ["assets/situ/girl-heiress-wed.webp", "그 집 딸은 내 회사 기획실장이었다."],
      ["assets/situ/guy-01-night.webp", "나를 무너뜨렸어야 할 재무이사는<br>형을 감시하고 있었다."],
      ["assets/situ/heroine-night.webp", "나를 배신했어야 할 여자는<br>내 이름도 모른 채 잘 살고 있었다."],
      ["assets/situ/guy-08-gift.webp", "그리고 형은<br>내 협력업체 사장이었다."],
      ["assets/mc-38-lux-06.png", "전생에 나를 밟았던 순서대로<br>전부 뒤집었다."],
      ["assets/mc-38-lux-07.png", "완벽했다."],
      ["assets/situ/girl-09-gift.webp", "어머니가 물었다.<br>“요즘 형이랑은 잘 지내니.”"],
      ["assets/mc-38-lux-08.png", "“네, 잘 지내요.”"],
      ["assets/situ/girl-10-gift.webp", "어머니는 그 말을 믿었다."],
      ["assets/mc-38-lux-09.png", "나는 어머니한테<br>아무것도 말하지 않았다."],
      ["assets/situ/guy-09-date.webp", "그해 12월, 회식이 있었다."],
      ["assets/situ/guy-09-gift.webp", "형이 술잔을 들고 다가왔다."],
      ["assets/mc-38-lux-10.png", "나는 방심하고 있었다.<br>이겼다고 생각했으니까."],
      ["assets/situ/guy-08-sad.webp", "형이 내 귀에 대고 조용히 말했다."],
      ["assets/situ/guy-08-night.webp", "“너 <b>2020년 3월</b> 알지?”", "shock", "?!"],
    ],
  },
  {
    no: "9화",
    title: "형도 회귀자였다",
    log: "이겼다고 믿은 7년이 통째로 뒤집힌다. 형은 나보다 먼저 회귀했고, 내가 이기는 걸 알면서 놔뒀다.",
    cuts: [
      ["assets/mc-26.webp", "술잔을 놓쳤다."],
      ["assets/situ/guy-08-night-2.webp", "“왜 그래. 얼굴이 하얘졌네.”", "q"],
      ["assets/mc-27.webp", "2020년 3월을 아는 사람은<br>이 세상에 나뿐이어야 했다."],
      ["assets/situ/guy-08-night-3.webp", "“나 말이야, <b>너보다 먼저</b> 왔어.”", "shock", "반전"],
      ["assets/mc-28.webp", "머리가 하얘졌다."],
      ["assets/situ/guy-08-travel.webp", "“도장 바꿔치기, 잘하더라.<br>열여덟에 그 생각을 해?”"],
      ["assets/mc-29.webp", "형은 <b>알고 있었다.</b><br>2010년 그때부터.", "shock", "알고 있었다"],
      ["assets/situ/guy-08-date.webp", "“특허도 그렇고, 지분 매집도 그렇고.<br>다 봤어. 처음부터.”"],
      ["assets/mc-30.webp", "그럼 왜 안 막았느냐고 물었다."],
      ["assets/situ/guy-08-wed.webp", "“막을 이유가 뭐 있어.<br><b>네가 키운 걸 뺏는 게</b> 더 싸잖아.”", "shock", "설계"],
      ["assets/mc-31.webp", "7년을 이겼다고 생각했다."],
      ["assets/situ/guy-01-sad.webp", "그 7년이 통째로<br>형의 계획이었다."],
      ["assets/mc-32.webp", "전생에도 그랬다.<br>내가 회사를 키울 때까지 기다렸다가<br>딱 상장 직전에 삼켰다."],
      ["assets/situ/guy-08-gift.webp", "“이번엔 상장 안 하잖아.<br>그래서 다른 걸 준비했지.”", "q"],
      ["assets/mc-33.webp", "무슨 소리냐고 물었다."],
      ["assets/situ/guy-10-date.webp", "형이 봉투를 하나 내밀었다."],
      ["assets/situ/guy-10-gift.webp", "7화에서 내가 내민<br>서른두 장짜리 계약서였다.", "shock", "그 계약서"],
      ["assets/mc-34.webp", "“이거 말이야.<br>19쪽에 뭐가 있는지 알아?”"],
      ["assets/mc-35.webp", "내가 직접 만든 계약서였다.<br>변호사 다섯이 검토했다."],
      ["assets/situ/guy-08-night-4.webp", "“근데 그 변호사,<br>누가 소개했더라?”", "next", "NEXT"],
    ],
  },
  {
    no: "10화",
    title: "내가 판 함정에 내가 빠졌다",
    log: "내 계약서 19쪽에는 내가 넣지 않은 조항이 있었다. 이번엔 위조가 아니다. 내가 서명한 진짜 계약서였다.",
    cuts: [
      ["assets/situ/guy-11-date.webp", "계약서 19쪽을 펼쳤다."],
      ["assets/situ/guy-11-gift.webp", "내가 넣지 않은 조항이 있었다."],
      ["assets/mc-36.webp", "경영권 분쟁 시<br>지분을 액면가에 넘긴다는 조항.", "shock", "19쪽"],
      ["assets/situ/guy-11-night.webp", "전생엔 위조 계약서였다."],
      ["assets/mc-37.webp", "이번엔 <b>내가 서명한 진짜</b>였다.", "shock", "진짜"],
      ["assets/situ/guy-12-date.webp", "변호사를 소개한 건<br>그 집 딸이었다."],
      ["assets/situ/girl-heiress-night-3.webp", "6화에서 내가 넘긴 그 눈빛.<br>그게 이거였다.", "shock", "복선 회수"],
      ["assets/mc-38.webp", "그 여자는 형 편이었다.<br>처음부터."],
      ["assets/situ/girl-heiress-night-4.webp", "“오빠가 우리 집을 뺏었잖아요.”", "q"],
      ["assets/situ/guy-12-gift.webp", "다음 날 임시주총이 열렸다."],
      ["assets/situ/guy-12-night.webp", "내 지분이 액면가에 넘어갔다.", "shock", "경영권"],
      ["assets/mc-38-lux-01.png", "열 살부터 15년을 쌓은 게<br>하루 만에 사라졌다."],
      ["assets/situ/guy-13-date.webp", "그리고 고소가 들어왔다."],
      ["assets/situ/guy-13-gift.webp", "배임. 액수는 480억."],
      ["assets/mc-38-lux-02.png", "내가 형 회사에 넣은 10억이<br>배임 증거가 됐다.", "shock", "배임"],
      ["assets/situ/guy-13-night.webp", "계좌가 동결됐다."],
      ["assets/situ/guy-14-date.webp", "1심 유죄. 2심에서 확정."],
      ["assets/mc-38-lux-04.png", "<b>징역 2년.</b>", "shock", "실형"],
      ["assets/situ/guy-14-gift.webp", "수감되던 날 형이 면회를 왔다."],
      ["assets/situ/guy-08-sad.webp", "“고생해라. 형이 회사 잘 지킬게.”", "next", "NEXT"],
    ],
  },
  {
    no: "11화",
    title: "형이 모르는 게 하나 있다",
    log: "미래 지식은 감옥에서 쓸모가 없다. 형은 내 모든 수를 알고 있다. 딱 하나, 2005년에 심어둔 사람만 빼고.",
    cuts: [
      ["assets/situ/guy-14-night.webp", "2015년 겨울. 수감."],
      ["assets/mc-26.webp", "미래를 아는 게 무기라고 믿었다."],
      ["assets/mc-27.webp", "형도 아니까<br>그건 무기가 아니었다."],
      ["assets/situ/guy-15-date.webp", "2년이면 기억의 유효기간도<br>2년 줄어든다."],
      ["assets/mc-28.webp", "2017년에 나오면<br>남은 건 9년치."],
      ["assets/situ/guy-15-gift.webp", "형은 내가 아는 걸 전부 안다."],
      ["assets/mc-29.webp", "내가 뭘 살지, 언제 팔지,<br>어디로 도망갈지까지."],
      ["assets/situ/guy-15-night.webp", "딱 하나만 빼고."],
      ["assets/situ/guy-01-wed.webp", "2005년에 형 옆에 심어둔 사람.", "gold", "유일한 카드"],
      ["assets/mc-30.webp", "형은 그 사람을 <b>자기 사람</b>이라고 믿는다."],
      ["assets/situ/guy-01-travel.webp", "전생에 그 사람은<br>형 편이었으니까."],
      ["assets/mc-31.webp", "형의 기억 속에서도 그렇다."],
      ["assets/mc-32.webp", "형은 회귀자다.<br>그래서 <b>전생의 기억을 믿는다.</b>", "gold", "급소"],
      ["assets/situ/guy-01-night.webp", "그게 형의 유일한 빈틈이었다."],
      ["assets/situ/girl-11-gift.webp", "면회 오는 사촌 편에<br>쪽지 한 장을 보냈다."],
      ["assets/mc-33.webp", "‘지금부터 형 계좌를 전부 기록해 주세요.’"],
      ["assets/situ/girl-12-gift.webp", "두 달 뒤 답이 왔다.<br>‘차명 47개입니다.’", "win", "47개"],
      ["assets/mc-34.webp", "형은 전생 그대로 움직이고 있었다."],
      ["assets/mc-35.webp", "같은 은행, 같은 명의, 같은 순서."],
      ["assets/situ/guy-02-wed.webp", "2017년 겨울. 출소.", "next", "NEXT"],
    ],
  },
  {
    no: "12화",
    title: "12년 전에 심어둔 사람",
    log: "출소한 나에게는 아무것도 없다. 하지만 2005년에 형 옆에 앉힌 사람이 12년째 그 자리에 있었다.",
    cuts: [
      ["assets/situ/guy-02-travel.webp", "2017년 겨울. 출소.<br>주머니에 5만원이 있었다."],
      ["assets/mc-36.webp", "집도, 회사도, 이름도 없었다."],
      ["assets/situ/guy-03-travel.webp", "고시원 3층에 방을 얻었다."],
      ["assets/mc-37.webp", "형은 내가 끝났다고 믿었다."],
      ["assets/situ/guy-01-date.webp", "일주일 뒤, 한 사람이 찾아왔다."],
      ["assets/situ/guy-01-gift.webp", "12년째 형 옆에 앉아 있는<br>그 회계사였다.", "win", "회수"],
      ["assets/mc-38.webp", "“약속 지키러 왔습니다.”"],
      ["assets/situ/guy-01-sad.webp", "“<b>딱 한 번만</b> 편들어달라고 하셨죠.”", "q"],
      ["assets/mc-38-lux-05.png", "목이 막혀서 말이 안 나왔다."],
      ["assets/situ/guy-01-night.webp", "그가 USB 하나를 놓고 갔다."],
      ["assets/situ/guy-04-wed.webp", "차명 계좌 47개의<br>12년치 자금 흐름이었다.", "gold", "증거"],
      ["assets/mc-38-lux-06.png", "형이 나를 감옥에 넣을 때<br>쓴 돈의 출처까지 있었다."],
      ["assets/situ/guy-05-wed.webp", "바로 검찰에 넘길 수도 있었다."],
      ["assets/mc-38-lux-07.png", "넘기지 않았다."],
      ["assets/situ/guy-06-wed.webp", "형이 무너지는 것보다<br>더 중요한 게 있었다."],
      ["assets/mc-38-lux-08.png", "2020년 3월.<br>형이 <b>전 재산을 거는 날</b>이다.", "gold", "급소"],
      ["assets/situ/guy-07-wed.webp", "회귀자는 확신하는 순간에만<br>전부를 건다."],
      ["assets/mc-38-lux-09.png", "그날 형을 무너뜨리면<br>회사도 돈도 한 번에 돌아온다."],
      ["assets/situ/guy-08-night-2.webp", "나는 3년을 조용히 기다렸다."],
      ["assets/situ/guy-08-travel.webp", "형은 내가 폐인이 된 줄 알았다.", "next", "NEXT"],
    ],
  },
  {
    no: "13화",
    title: "반대매매는 바닥보다 먼저 온다",
    log: "형은 2020년 3월 19일 바닥을 안다. 나도 안다. 하지만 형이 모르는 건 3월 17일에 무슨 일이 일어나는가다.",
    cuts: [
      ["assets/situ/guy-09-wed.webp", "2020년 1월. 뉴스에 낯익은 단어가 나왔다."],
      ["assets/mc-26.webp", "코로나. 기억대로였다."],
      ["assets/situ/guy-08-date.webp", "형이 움직이기 시작했다."],
      ["assets/situ/guy-08-gift.webp", "2월. 보유 자산 전량을 담보로<br>레버리지를 최대로 당겼다.", "shock", "올인"],
      ["assets/mc-27.webp", "맞는 판단이었다.<br>3월 19일이 바닥이니까."],
      ["assets/situ/guy-10-wed.webp", "형은 그날만 보고 있었다."],
      ["assets/mc-28.webp", "문제는 3월 19일까지<br><b>버틸 수 있느냐</b>였다.", "gold", "급소"],
      ["assets/situ/guy-11-wed.webp", "레버리지는 바닥을 못 기다린다."],
      ["assets/mc-29.webp", "담보 비율이 무너지면<br>증권사가 알아서 판다."],
      ["assets/mc-30.webp", "<b>반대매매는 바닥보다 먼저 온다.</b> 항상.", "gold", "규칙"],
      ["assets/situ/guy-12-wed.webp", "전생엔 형이 이걸 안 겪었다.<br>그땐 내 돈으로 버텼으니까."],
      ["assets/mc-31.webp", "이번엔 내 돈이 없다."],
      ["assets/situ/guy-13-wed.webp", "3월 12일. 첫 마진콜."],
      ["assets/situ/guy-14-wed.webp", "3월 16일. 두 번째."],
      ["assets/mc-32.webp", "형이 급하게 돈을 구하러 다녔다."],
      ["assets/situ/guy-01-travel.webp", "그 회계사가<br>“자금이 없습니다”라고 보고했다.", "win", "안에서"],
      ["assets/situ/guy-15-wed.webp", "3월 17일 오전 9시 3분.<br>강제청산.", "shock", "청산"],
      ["assets/mc-33.webp", "나는 그 물량을 전부 받았다.", "win", "인수"],
      ["assets/mc-34.webp", "3월 19일. 바닥이 왔다.<br>그리고 기억대로 올랐다."],
      ["assets/car-rolls.png", "2021년.<br>회사가 내 이름으로 돌아왔다.", "next", "NEXT"],
    ],
  },
  {
    no: "14화",
    title: "회장이 형을 버렸다",
    log: "무너진 형에게 그 집안은 아무 쓸모가 없다. 회장은 딸을 데리고 나에게 왔다.",
    cuts: [
      ["assets/situ/guy-heir-date.webp", "그 집안 회장이 먼저 연락해왔다."],
      ["assets/situ/guy-heir-gift.webp", "“오해가 있었던 것 같네.”", "q"],
      ["assets/mc-35.webp", "오해가 아니라 계산이었다.<br>이번 계산도 마찬가지고."],
      ["assets/situ/guy-heir-travel.webp", "회장이 딸을 데려왔다."],
      ["assets/situ/girl-heiress-sad.webp", "10화에서 나를 판 그 여자였다."],
      ["assets/mc-36.webp", "고개를 못 들고 있었다."],
      ["assets/situ/girl-heiress-date.webp", "“그때는… 아버지가 시켜서.”", "q"],
      ["assets/mc-37.webp", "나는 그 말을 믿지 않았다."],
      ["assets/situ/girl-heiress-gift.webp", "다만 그 여자가 가진 게 하나 있었다."],
      ["assets/situ/girl-heiress-travel.webp", "형에게 넘어간 지분 <b>18%</b>."],
      ["assets/mc-38.webp", "받았다. 대신 각서를 썼다.<br>이번엔 서른두 장이 아니라 두 장.", "win", "18%"],
      ["assets/situ/guy-heir-night.webp", "회장은 자리에서 물러났다."],
      ["assets/situ/guy-heir-wed.webp", "그 집안이 다시 내 계열사가 됐다."],
      ["assets/mc-38-lux-01.png", "형에게 남은 건 껍데기였다."],
      ["assets/situ/guy-08-sad.webp", "형이 협력업체 등록을 신청했다."],
      ["assets/mc-38-lux-02.png", "5화에서 형이 그랬던 것처럼."],
      ["assets/situ/guy-08-night-3.webp", "나는 반려했다."],
      ["assets/mc-38-lux-04.png", "이번엔 밑에 두지 않았다."],
      ["assets/situ/guy-08-night-4.webp", "형이 회사 앞에서 나를 기다렸다."],
      ["assets/situ/guy-08-wed.webp", "“…어머니가 너 보고 싶어 하신다.”", "next", "NEXT"],
    ],
  },
  {
    no: "15화",
    title: "어머니는 12년을 속았다",
    log: "어머니는 아직도 내가 회삿돈을 들고 도망친 아들이라고 알고 있다. 형이 1화에서 그렇게 말했으니까.",
    cuts: [
      ["assets/situ/girl-13-gift.webp", "어머니는 요양병원에 있었다."],
      ["assets/mc-38-lux-05.png", "12년 만이었다."],
      ["assets/situ/girl-14-gift.webp", "들어가자 어머니가 나를 봤다."],
      ["assets/situ/girl-15-gift.webp", "“너… 이제 돈은 다 갚았니?”", "q"],
      ["assets/mc-38-lux-06.png", "어머니는 아직도<br>내가 회삿돈을 들고 도망쳤다고<br>알고 있었다.", "shock", "12년"],
      ["assets/situ/guy-08-date.webp", "1화에서 형이 한 말이<br>12년을 살아 있었다."],
      ["assets/mc-38-lux-07.png", "나는 아무 말도 못 했다."],
      ["assets/situ/girl-16-gift.webp", "증거는 있었다. USB 하나면 끝이었다."],
      ["assets/mc-38-lux-08.png", "그런데 그걸 보여주면<br>어머니는 형을 잃는다."],
      ["assets/situ/girl-17-sad.webp", "어머니가 스무 해를 아들이라 부른 사람이다."],
      ["assets/mc-38-lux-09.png", "전생에 나는 그걸 몰랐다.<br>어머니는 형을 더 예뻐했으니까."],
      ["assets/situ/girl-18-sad.webp", "“엄마, 나 돈 다 갚았어.”"],
      ["assets/mc-38-lux-10.png", "거짓말을 했다.<br>처음으로 이기는 게 싫었다."],
      ["assets/situ/girl-19-sad.webp", "어머니가 내 손을 잡았다."],
      ["assets/mc-26.webp", "“고생했다.”"],
      ["assets/situ/guy-08-gift.webp", "문밖에 형이 서 있었다.<br>다 듣고 있었다."],
      ["assets/mc-27.webp", "형 얼굴이 처음으로 무너졌다.", "shock", "균열"],
      ["assets/situ/guy-08-night.webp", "“…왜 말 안 했어.”", "q"],
      ["assets/mc-28.webp", "“어머니 아들은 둘이잖아.”"],
      ["assets/int-rooftop-2.webp", "형이 그날 밤 문자를 보냈다.<br>‘내일 그 옥상에서 보자.’", "next", "NEXT"],
    ],
  },
  {
    no: "16화",
    title: "이번엔 내가 난간 밖에 서 있지 않았다",
    log: "2026년 7월. 처음 뛰어내리려던 그 옥상. 이번엔 형이 난간에 서 있다.",
    cuts: [
      ["assets/int-rooftop-3.webp", "2026년 7월 15일. 그 옥상."],
      ["assets/situ/guy-08-night-2.webp", "형이 난간에 서 있었다."],
      ["assets/mc-29.webp", "전생에 내가 서 있던 자리였다."],
      ["assets/situ/guy-08-sad.webp", "“나는 세 번 살았어.”", "shock", "세 번"],
      ["assets/mc-30.webp", "세 번."],
      ["assets/situ/guy-08-travel.webp", "“첫 번째는 아무것도 몰라서 망했고,”"],
      ["assets/situ/guy-08-night-3.webp", "“두 번째에 너를 밟았지.<br>세 번째도 그럴 줄 알았는데.”"],
      ["assets/mc-31.webp", "“근데 왜 이번엔 안 됐는지 알아?”"],
      ["assets/situ/guy-01-date.webp", "2005년에 심은 사람 하나.", "gold", "12년 전 한 수"],
      ["assets/mc-32.webp", "형은 전생의 기억을 믿었다.<br>그 사람은 자기 편이라고."],
      ["assets/situ/guy-01-sad.webp", "회귀자의 약점은 미래가 아니라<br><b>과거를 믿는 것</b>이었다.", "gold", "급소"],
      ["assets/situ/guy-08-night-4.webp", "형이 웃었다. “그래서 뭐.”"],
      ["assets/mc-33.webp", "나는 USB를 꺼냈다."],
      ["assets/situ/guy-02-date.webp", "차명 47개, 12년치 자금 흐름."],
      ["assets/mc-34.webp", "“미래를 아는 건 죄가 아니야.<br>근데 <b>이건 죄야.</b>”", "win", "증거"],
      ["assets/situ/guy-02-gift.webp", "형이 난간에서 내려왔다."],
      ["assets/situ/guy-03-date.webp", "경찰이 옥상으로 올라왔다.", "win", "최종"],
      ["assets/mc-35.webp", "형이 끌려가면서 물었다.<br>“어머니한텐 뭐라고 할 거냐.”"],
      ["assets/mc-36.webp", "“형은 출장 갔다고 할게.”"],
      ["assets/title-hero.png", "2026년 7월.<br>이번엔 내가 난간 밖에<br>서 있지 않았다.", "next", "PLAY"],
    ],
  },
];
