// 나 혼자만 상한가 — SNS 홍보 웹툰 대본
// 컷 형식: [이미지 경로, 캡션(<br> 줄바꿈), 종류(shock|win|gold|next|q), 스탬프]
// 이미지는 전부 게임(sanghanga-web) 저장소의 기존 에셋이며, 320컷이 서로 다른 그림을 쓴다.
//
// 연표 — 1988년생. 1998년(10세) 회귀. 2026년(38세) 완결.
//   1998 회귀 / 2006 도장 / 2008 부도 저지 / 2009 재무이사 / 2011 특허
//   2013 지분 공개 / 2014 계약서 / 2015 자산 1조·형의 정체 / 2016 수감
//   2018 출소 / 2020 반대매매·회장·어머니 / 2026 옥상

const LEDE = "옥상에서 떨어진 남자가 열 살로 돌아갔다. 그를 밟은 사람은 스무 해를 형이라 부른 사람이었다. " +
  "이번 생에서 그는 형을 막지 않는다. 형이 무엇을 언제 훔칠지 전부 알고 있으니까. 전 16화.";

const EPISODES = [
{
  no: "EP.01", title: "오늘부터 네 형이다",
  log: "2026년, 상장을 두 달 앞두고 내 도장이 찍힌 각서 한 장이 나타났다.",
  cuts: [
    ["assets/mc-38.webp", "2026년 7월. 서른여덟.<br>회사 지분 60%, 가을엔 상장이었다.<br>나는 다 가진 줄 알았다."],
    ["assets/situ/guy-05-date.webp", "형은 내가 열 살이던 해에 우리 집에 왔다.<br>아버지 친구의 아들이었고,<br>사고로 부모를 한꺼번에 잃었다고 했다."],
    ["assets/situ/girl-legend-1-gift.webp", "어머니는 사흘도 안 돼<br>밥상에 수저를 하나 더 놓았다.<br>\"오늘부터 네 형이다.\"", "q"],
    ["assets/mc-teen.webp", "나는 형이 생겨서 좋았다.<br>학교에서 맞고 온 날<br>대신 찾아가 준 사람이 형이었다."],
    ["assets/situ/guy-05-travel.webp", "스물여섯에 같이 회사를 차렸다.<br>자본금 3천만원, 지분은 반씩.<br>계약서는 쓰지 않았다. 형제니까."],
    ["assets/mc-26.webp", "3년을 라면으로 버텼다.<br>거래처 문턱 하나 넘으려고<br>하루에 열두 번 고개를 숙였다."],
    ["assets/dc/dc-05.webp", "서른둘에 첫 흑자가 났다.<br>그해 어머니가 형을 앉혀놓고<br>내 지분에서 40%를 떼어 줬다."],
    ["assets/situ/girl-legend-1-sad.webp", "\"형이 없었으면 너도 없었다.\"<br>나는 웃으면서 도장을 찍었다.<br>이번에도 계약서는 없었다.", "q"],
    ["assets/fmc-30.webp", "서른다섯에 그 여자를 만났다.<br>회사 창립 기념일 자리에<br>형이 데려온 사람이었다."],
    ["assets/lux-tiffany.png", "반년 만에 무릎을 꿇고 반지를 내밀었다.<br>그 여자는 울면서 손을 내밀었다.<br>그날이 정확히 3년 전 오늘이다."],
    ["assets/int-betrayal.webp", "상장 실사 이틀 전.<br>회계법인이 서류 한 장을 보내왔다.<br>내가 본 적 없는 각서였다.", "shock", "배신"],
    ["assets/dc/dc-12.webp", "지분 60% 전부를 형에게 넘긴다는 내용.<br>맨 아래에 내 인감이 찍혀 있었다.<br>날짜는 형 생일상을 차려주던 주였다."],
    ["assets/int-betrayal-2.webp", "위조였다. 증명하면 될 일이었다.<br>그런데 그 인감을 금고에서 꺼낼 수 있는 사람이<br>회사에 나 말고 한 명 더 있었다.", "shock"],
    ["assets/fmc-33.webp", "그날 밤 약혼녀가 먼저 입을 열었다.<br>\"나 임신했어.\"<br>나는 웃었다. 딱 3초 동안.", "q"],
    ["assets/int-betrayal-3.webp", "\"임신은 거짓말 아니야.<br>근데 네 아이가 아니야.\"<br>3년 전부터라고 했다.", "shock", "막장"],
    ["assets/lux-flap.png", "내가 청혼하던 그날 밤에도<br>그 여자는 형의 차를 타고 집에 갔다.<br>나는 그걸 3년 동안 몰랐다."],
    ["assets/situ/guy-15-night.webp", "다음 날 형이 전 직원에게 메일을 돌렸다.<br>'대표가 회삿돈을 들고 잠적했습니다.'<br>발신 시각은 새벽 4시였다.", "shock"],
    ["assets/situ/girl-legend-1-night.webp", "어머니한테도 똑같이 말했다.<br>어머니는 내 전화를 받지 않았다.<br>스무 해를 아들이라 부른 쪽을 믿었다."],
    ["assets/int-betrayal-4.webp", "통장이 묶이고 명의가 넘어가고<br>고소장이 세 건 들어왔다.<br>전부 2주 안에 벌어진 일이었다.", "shock"],
    ["assets/int-rooftop.webp", "7월 15일. 남은 건 빚 17억.<br>나는 옥상 난간 밖에 서 있었다.<br>비가 오는데 우산 쓴 사람이 하나도 없었다.", "next", "NEXT"],
  ]
},
{
  no: "EP.02", title: "도장이 안 맞는대",
  log: "떨어지는 순간 1998년으로 돌아갔다. 형이 우리 집에 오기 두 달 전이었다.",
  cuts: [
    ["assets/int-rooftop-2.webp", "발을 뗐다.<br>떨어지는 데 걸린 시간은<br>1초도 안 됐던 것 같다."],
    ["assets/int-wake.webp", "눈을 떴을 때 천장이 낮았다.<br>스무 해 전에 도배를 새로 한 내 방이었다.<br>손이 작았다.", "shock"],
    ["assets/mc-boy.webp", "열 살이었다.<br>책상에 1998년 달력이 놓여 있었고<br>서랍에는 용돈 3만원이 있었다."],
    ["assets/seed/hang.webp", "회귀. 그 단어를 떠올리는 데 이틀,<br>그게 진짜라고 믿는 데<br>일주일이 걸렸다."],
    ["assets/dc/dc-01.webp", "달력을 다시 셌다.<br>형이 우리 집에 오기 두 달 전이었다.<br>막을 수 있는 시간이 남아 있었다."],
    ["assets/situ/guy-05-gift.webp", "아버지한테 한마디만 하면 됐다.<br>저 집 애는 받지 말자고.<br>그런데 나는 아무 말도 하지 않았다.", "shock"],
    ["assets/mc-10.webp", "형이 안 오면 형은 다른 집에 간다.<br>거기서 무슨 짓을 할지는 내가 모른다.<br>아는 자리에 둬야 막을 수 있다."],
    ["assets/situ/guy-05-night.webp", "두 달 뒤 형이 왔다.<br>현관에서 나를 보고 웃었다.<br>나는 이번에도 웃어줬다."],
    ["assets/mc-11.webp", "그날부터 노트를 썼다.<br>전생의 12년을 날짜까지 적었다.<br>형이 언제 무엇을 훔치는지 전부.", "win"],
    ["assets/dc/dc-03.webp", "첫 번째는 2006년이었다.<br>형이 어머니 인감을 들고 나가<br>5천만원을 빌린다."],
    ["assets/mc-12.webp", "그 돈은 두 달 만에 사라지고<br>보증을 선 아버지 공장이 넘어갔다.<br>우리 집이 무너진 건 거기서부터였다."],
    ["assets/lux-signet.png", "나는 열여덟에 그 인감을 바꿔놨다.<br>새로 파서 구청 신고까지 마쳤다.<br>어머니는 끝까지 몰랐다.", "win"],
    ["assets/situ/guy-05-sad.webp", "2006년 봄, 형이 은행 창구 앞에<br>한참을 서 있었다고 한다.<br>\"이상하네. 도장이 안 맞는대.\"", "q", "첫 반격"],
    ["assets/girl-legend-1.png", "어머니가 나한테 물었다.<br>\"너 혹시 도장 어디 있는지 아니?\"<br>\"몰라요.\" 나는 그렇게 말했다.", "q"],
    ["assets/mc-13.webp", "5천만원이 나가지 않았다.<br>공장이 넘어가지 않았다.<br>아버지가 3년을 더 살았다.", "win"],
    ["assets/situ/guy-15-sad.webp", "형은 결국 다른 데서 돈을 구했다.<br>사채였다. 이자가 월 15%.<br>나는 알면서 두고 봤다.", "shock"],
    ["assets/loanshark.webp", "그해 겨울, 형 방에<br>낯선 남자 둘이 다녀갔다.<br>형이 처음으로 내 앞에서 울었다."],
    ["assets/mc-14.webp", "갚아줄 수 있었다. 안 갚아줬다.<br>전생에 내가 받은 게<br>정확히 그거였으니까."],
    ["assets/situ/guy-05-wed.webp", "그때부터 형이 나를 보는 눈이 달라졌다.<br>고마움이 아니라 계산이었다.<br>전생에도 똑같은 눈이었다."],
    ["assets/int-flash.webp", "다음은 2008년이다.<br>형이 한 여자를 만나 인생을 갈아타는 해.<br>이번엔 내가 먼저 간다.", "next", "NEXT"],
  ]
},
{
  no: "EP.03", title: "내가 먼저 살렸다",
  log: "전생의 그 여자는 부도난 아버지 회사를 형이 살려줘서 형에게 갔다. 그럼 부도를 막으면 된다.",
  cuts: [
    ["assets/fmc-20.webp", "2008년에 형이 만난 여자.<br>전생에 내 약혼녀가 됐고<br>내 아이를 가졌다고 거짓말한 사람이다."],
    ["assets/dc/dc-07.webp", "그 여자를 처음 만난 자리를 나는 안다.<br>아버지 회사가 부도난 다음 날,<br>채권단 사무실 복도였다."],
    ["assets/situ/guy-15-travel.webp", "형은 그날 빚 8억을 대신 갚아줬다.<br>돈이 어디서 났는지는 아무도 안 물었다.<br>사채였다. 그것도 내가 안다."],
    ["assets/fmc-21.webp", "그 여자는 그걸 평생 갚을 빚으로 여겼다.<br>사랑이 아니라 부채였다.<br>그래서 형이 시키는 건 뭐든 했다."],
    ["assets/mc-19.webp", "그럼 부도를 안 나게 하면 된다.<br>빚이 없으면 갚아줄 것도 없고<br>갚아줄 게 없으면 만날 이유도 없다.", "win"],
    ["assets/logos/logo-03.png", "그 회사 이름을 노트에서 찾았다.<br>부품업체였고, 직원이 서른 명이었고,<br>부도일은 2008년 3월 14일이었다."],
    ["assets/mc-20.webp", "스무 살. 나한테는 돈이 없었다.<br>대신 전생에서 가져온 게 하나 있었다.<br>2007년에 뭐가 오르는지 아는 머리."],
    ["assets/dc/dc-09.webp", "2007년 한 해 동안<br>등록금과 알바비를 굴려 3천만원을 만들었다.<br>노트에 적힌 종목만 샀다.", "win"],
    ["assets/mc-21.webp", "부도 나흘 전, 그 회사를 찾아갔다.<br>스무 살짜리가 자금 얘기를 하니<br>경리부장이 웃었다."],
    ["assets/vip/commo-m.webp", "\"3천이면 어음 하나 막습니다.<br>대신 지분 12% 주십시오.\"<br>대표는 30분 만에 도장을 찍었다.", "q"],
    ["assets/logos/logo-06.png", "3월 14일이 지나갔다.<br>부도가 나지 않았다.<br>직원 서른 명이 그대로 출근했다.", "win", "저지"],
    ["assets/situ/girl-12-date.webp", "그 여자는 그해에<br>휴학하지 않았고, 채권단 복도에 서지 않았고,<br>형을 만나지 않았다."],
    ["assets/situ/guy-15-gift.webp", "그해 겨울, 형이 그 집 앞을 두 번 서성였다.<br>갚아줄 빚이 없으니<br>말을 걸 명분이 없었다.", "win"],
    ["assets/situ/girl-12-travel.webp", "그 여자는 다른 사람과 결혼했다.<br>청첩장이 회사로 왔다.<br>내 이름은 하객 명단에 없었다."],
    ["assets/mc-22.webp", "복수는 되갚는 게 아니라<br>애초에 안 만나게 하는 것일 수도 있다.<br>그걸 스무 살에 배웠다."],
    ["assets/situ/guy-15-date.webp", "형은 그해 사채 이자를 못 막고<br>학교를 그만뒀다.<br>전생에는 없던 일이었다.", "win"],
    ["assets/situ/guy-16-sad.webp", "형이 나를 찾아와 돈을 빌려달라고 했다.<br>\"형제끼리 이러기냐.\"<br>전생에 내가 형한테 한 말이었다.", "q"],
    ["assets/mc-23.webp", "3천만원은 12%가 되어 돌아왔다.<br>그 지분은 3년 뒤<br>내 첫 회사의 종잣돈이 된다."],
    ["assets/dc/dc-14.webp", "전생에 나를 무너뜨린 사람은 셋이었다.<br>여자 하나, 재무이사 하나, 그리고 형.<br>이제 하나 지웠다."],
    ["assets/int-flash-2.webp", "두 번째는 사람이 아니라 자리다.<br>형 옆자리.<br>거기에 내 사람을 앉힐 차례다.", "next", "NEXT"],
  ]
},
{
  no: "EP.04", title: "형 옆에 내 사람을 심었다",
  log: "전생에 나를 발가벗긴 재무이사를, 아직 무명이던 시절에 내가 먼저 찾아갔다.",
  cuts: [
    ["assets/guy-heir.png", "전생에 내 회사 재무이사였던 사람.<br>장부를 만들고, 숨기고,<br>마지막에 검찰에 넘긴 것도 그였다."],
    ["assets/dc/dc-16.webp", "그가 형 편에 선 이유는 단순했다.<br>형이 먼저 그를 찾아갔기 때문이다.<br>2011년, 그가 무명이던 때에."],
    ["assets/mc-24.webp", "그럼 2009년에 내가 먼저 가면 된다.<br>2년 빠르면 된다.<br>2년은 사람 하나를 사기에 충분하다.", "win"],
    ["assets/situ/guy-heir-sad.webp", "합격 2년 차 회계사였다.<br>사무실은 반지하였고<br>어머니 병원비가 밀려 있었다."],
    ["assets/situ/guy-heir-date.webp", "\"우리 형 회사에 들어가 주세요.<br>월급은 그쪽에서 받고,<br>같은 액수를 제가 따로 드립니다.\"", "q"],
    ["assets/vip/hedge-m.webp", "\"왜 그런 일을 시키십니까.\"<br>\"언젠가 형이 저를 죽이려 할 겁니다.<br>그때 딱 한 번만 제 편을 들어주세요.\"", "q"],
    ["assets/situ/guy-heir-gift.webp", "그는 사흘을 생각하고 돌아왔다.<br>조건이 하나 있다고 했다.<br>\"약속 못 지키면 그냥 가겠습니다.\"", "q"],
    ["assets/lux-briefcase.png", "그날 우리는 각서를 두 장 썼다.<br>한 장은 그가, 한 장은 내가 가졌다.<br>그게 12년을 간다.", "win", "포섭"],
    ["assets/situ/guy-16-travel.webp", "형은 그를 반겼다.<br>싸고 유능했으니까.<br>사람이 왜 싼지는 묻지 않았다."],
    ["assets/dc/dc-18.webp", "형은 그를 자기 사람이라고 불렀다.<br>회식 자리에서 어깨를 두드렸고<br>사업 계획을 전부 보여줬다."],
    ["assets/mc-25.webp", "그 사람 통장에 매달<br>내 돈이 따로 들어가는 건<br>형이 죽을 때까지 몰랐다.", "win"],
    ["assets/situ/guy-heir-travel.webp", "석 달에 한 번씩 만났다.<br>커피값은 늘 그가 냈다.<br>\"이건 제 돈으로 사고 싶습니다.\"", "q"],
    ["assets/dc/dc-20.webp", "그가 가져오는 건 문서가 아니었다.<br>형이 누구를 만나고,<br>무슨 말투로 거짓말하는지였다."],
    ["assets/situ/guy-16-gift.webp", "형은 2010년에 차명 계좌를 만들었다.<br>첫 번째 계좌 번호를<br>나는 그날 저녁에 알았다.", "win"],
    ["assets/lux-wallet.png", "그 계좌는 47개가 될 때까지 자란다.<br>나는 하나도 막지 않았다.<br>자라야 무기가 되니까."],
    ["assets/situ/guy-16-night.webp", "형은 자기가 나를 앞서고 있다고 믿었다.<br>내가 아는 걸 형은 몰랐고<br>형이 아는 건 내가 다 알았다."],
    ["assets/mc-27.webp", "전생엔 내가 발가벗겨졌다.<br>이번엔 형이 그렇다.<br>본인만 모르는 채로."],
    ["assets/situ/guy-heir-night.webp", "그가 딱 한 번 물었다.<br>\"형님이신데, 괜찮으십니까.\"<br>\"형이었던 적이 없습니다.\"", "q"],
    ["assets/dc/dc-22.webp", "사람 하나를 심는 데 2년,<br>그 사람이 쓰이는 데는 12년이 걸린다.<br>나는 그걸 기다릴 수 있었다."],
    ["assets/int-flash-3.webp", "세 번째는 물건이다.<br>전생에 내 회사를 삼킨 그 아이템.<br>이번엔 내가 먼저 낸다.", "next", "NEXT"],
  ]
},
{
  no: "EP.05", title: "네 아이템은 내가 먼저 냈다",
  log: "형이 특허를 내러 갔다. 이미 3년 전에 등록돼 있었고, 출원인은 내 이름이었다.",
  cuts: [
    ["assets/mc-28.webp", "2011년. 스물셋.<br>형이 재기하겠다며 아이템 하나를 꺼냈다.<br>나는 그게 뭔지 이미 알고 있었다."],
    ["assets/dc/dc-24.webp", "전생에 형은 그걸로 회사를 키웠고,<br>그 회사가 내 회사를 삼켰다.<br>내 이름이 지워진 게 그때였다."],
    ["assets/logos/glogo-g1.png", "형은 그게 자기 머리에서 나온 줄 안다.<br>사실은 전생의 기억이다.<br>그건 나중에야 알게 된다."],
    ["assets/mc-29.webp", "특허는 먼저 낸 사람이 임자다.<br>아이디어가 누구 것이냐는<br>아무도 묻지 않는다.", "win"],
    ["assets/situ/guy-heir-wed.webp", "재무이사가 형의 사업계획서를<br>초안 단계에서 넘겨줬다.<br>2008년 겨울이었다."],
    ["assets/lux-cufflinks.png", "나는 그 도면을 변리사에게 들고 갔다.<br>출원비 180만원.<br>3년치 알바비였다."],
    ["assets/logos/logo-08.png", "2008년 12월 출원,<br>2011년 3월 등록.<br>출원인 이름 한 칸에 내 이름이 들어갔다.", "win", "선점"],
    ["assets/situ/guy-16-date.webp", "2011년 여름, 형이 특허청에 갔다.<br>창구에서 화면을 보고<br>한참을 서 있었다고 한다."],
    ["assets/situ/guy-16-wed.webp", "\"이거 누가 냈는데요.\"<br>직원이 이름을 읽어줬다.<br>형은 세 번을 다시 물었다.", "q", "역전"],
    ["assets/mc-30.webp", "형이 그날 밤 우리 집에 왔다.<br>현관에서 나를 보고<br>처음으로 웃지 않았다."],
    ["assets/situ/guy-16-night-2.webp", "\"네가 어떻게 이걸 알아.\"<br>\"형이 술 마시고 다 얘기했잖아.\"<br>형은 그 말을 믿었다. 3년 동안.", "q"],
    ["assets/mc-31.webp", "그 아이템은 내가 사업화했다.<br>2011년 매출 40억,<br>2013년에 300억이 된다.", "win"],
    ["assets/dc/dc-26.webp", "직원 여섯으로 시작했다.<br>사무실은 형 회사에서<br>지하철 두 정거장 거리였다."],
    ["assets/situ/guy-16-night-3.webp", "형은 하청을 받겠다고 찾아왔다.<br>단가를 후려칠 수도 있었다.<br>그렇게 하지 않았다."],
    ["assets/lux-tie.png", "제값을 줬다. 계약 기간은 1년씩.<br>매년 갱신해야 하는 조건.<br>형은 그게 배려인 줄 알았다."],
    ["assets/mc-32.webp", "망하게 두면 형은 사라진다.<br>사라지면 어디서 뭘 하는지 모른다.<br>내 밑에 있어야 보인다.", "win"],
    ["assets/situ/guy-01-date.webp", "형은 협력업체 사장이 됐다.<br>명절마다 내 사무실에 왔고<br>내 앞에서 두 손으로 잔을 받았다."],
    ["assets/liq-wh1.png", "그 술자리에서 형이 말했다.<br>\"네가 잘돼서 나도 산다.\"<br>나는 잔을 부딪쳤다.", "q"],
    ["assets/mc-33.webp", "전생에 나를 밟은 순서대로<br>하나씩 뒤집는 중이었다.<br>여자, 사람, 물건. 남은 건 돈이다."],
    ["assets/int-flash-4.webp", "네 번째는 2008년 10월이다.<br>세상이 전부 무너지는 달.<br>나는 그날을 알고 있었다.", "next", "NEXT"],
  ]
},
{
  no: "EP.06", title: "리먼 때 사둔 지분",
  log: "그 집안이 합병을 제안했다. 나는 다른 서류를 꺼냈다. 2008년 10월에 사둔 지분이었다.",
  cuts: [
    ["assets/situ/guy-legend-1-date.webp", "전생에 내 회사를 최종적으로 삼킨 그룹.<br>회장은 인수 자리에서 나한테<br>\"고생했네\" 한마디만 했다.", "q"],
    ["assets/mc-34.webp", "그 그룹을 이기는 방법을 오래 생각했다.<br>매출로는 20년이 걸린다.<br>주식이라면 하루면 된다."],
    ["assets/dc/dc-28.webp", "2008년 10월, 리먼이 무너졌다.<br>모두가 팔았다.<br>나는 그게 바닥이라는 걸 알았다.", "win"],
    ["assets/mc-35.webp", "스무 살, 손에 3천이 있었다.<br>부품업체 지분 12%를 담보로<br>대출을 최대로 당겼다."],
    ["assets/liq-soju1.png", "그 회사 계열사 주가가<br>고점 대비 84% 빠져 있었다.<br>나는 3주에 걸쳐 나눠 담았다."],
    ["assets/logos/glogo-g4.png", "5년 동안 아무한테도 말하지 않았다.<br>배당은 전부 재투자했고<br>지분율은 조용히 17%가 됐다.", "win"],
    ["assets/situ/girl-heiress-date.webp", "2013년. 그 집 딸이 협상 자리에 나왔다.<br>스물여섯. 후계자 수업 중이라고 했다.<br>합병 조건을 먼저 읽어 내려갔다."],
    ["assets/vip/chaebol-f.webp", "\"오빠 회사 저희가 사겠습니다.<br>지금 값이면 나쁘지 않으실 텐데요.\"<br>전생에 들었던 문장 그대로였다.", "q"],
    ["assets/mc-36.webp", "나는 그쪽 서류를 펴지 않았다.<br>대신 가방에서<br>다른 서류를 꺼내 밀었다."],
    ["assets/dc/dc-30.webp", "명의개서 확인서.<br>2008년 10월부터의 매입 내역.<br>맨 아래에 숫자가 하나 있었다."],
    ["assets/situ/girl-heiress-sad.webp", "\"17%요.<br>그쪽 2대 주주가 접니다.\"<br>그 여자가 종이를 세 번 넘겨봤다.", "q", "역전"],
    ["assets/situ/guy-legend-1-sad.webp", "30분 뒤 회장이 직접 내려왔다.<br>웃으면서 악수를 청했는데<br>손이 떨리는 걸 나는 봤다."],
    ["assets/vip/chaebol-m.webp", "합병은 없던 일이 됐다.<br>대신 그 집안이<br>내 이사회에 자리를 하나 달라고 했다.", "win"],
    ["assets/mc-37.webp", "나는 반대로 요구했다.<br>그쪽 이사회에 내 자리를 달라고.<br>회장은 사흘 뒤에 받아들였다.", "win", "인수"],
    ["assets/lux-royaloak.png", "스물다섯에<br>전생의 최종 보스가<br>내 계열사가 됐다."],
    ["assets/situ/girl-heiress-travel.webp", "그 여자는 그 뒤로 자주 연락했다.<br>사업 얘기였고, 가끔 밥이었다.<br>나는 대충 받아줬다."],
    ["assets/situ/girl-heiress-gift.webp", "\"오빠는 왜 다 알고 있는 것처럼 굴어요?\"<br>웃으면서 한 말이었다.<br>나는 그 눈빛을 대수롭지 않게 넘겼다.", "q"],
    ["assets/mc-38-lux-01.png", "그게 3년 뒤에<br>나를 감옥에 보낸다.<br>그때는 몰랐다.", "shock"],
    ["assets/dc/dc-02.webp", "여자, 사람, 물건, 돈.<br>전생에 나를 밟은 네 가지를<br>전부 뒤집었다."],
    ["assets/int-flash-5.webp", "그런데 형이 아직 살아 있다.<br>망하지도, 사라지지도 않고<br>내 밑에서 웃고 있다.", "next", "NEXT"],
  ]
},
{
  no: "EP.07", title: "형이 무릎을 꿇었다",
  log: "형이 나를 국밥집으로 불렀다. 전생에 우리가 창업을 결심한 바로 그 자리였다.",
  cuts: [
    ["assets/situ/guy-16-night-4.webp", "2014년 겨울, 형이 보자고 했다.<br>장소가 그 국밥집이었다.<br>전생에 우리가 창업을 결심한 자리."],
    ["assets/dc/dc-04.webp", "형은 자리를 미리 잡아놓고 있었다.<br>구석 자리, 창가.<br>전생에 앉았던 그 자리였다."],
    ["assets/situ/guy-16-night-5.webp", "\"10억만 넣어줘.<br>지분은 네가 60 가져가.\"<br>전생에 내가 형한테 했던 말이었다.", "q"],
    ["assets/mc-38-lux-02.png", "그때 형은 40을 가져가고<br>계약서는 안 썼다.<br>이번엔 비율만 반대였다."],
    ["assets/situ/guy-16-night-6.webp", "\"우리 사이에 계약서가 필요하냐.\"<br>형이 웃으면서 말했다.<br>그 문장도 전생 그대로였다.", "q"],
    ["assets/lux-alhambra.png", "나는 가방에서 서류를 꺼냈다.<br>서른두 장짜리 투자계약서.<br>변호사 셋이 두 달을 만졌다."],
    ["assets/situ/guy-17-sad.webp", "형이 열두 쪽에서 멈췄다.<br>연대보증 조항이었다.<br>얼굴이 하얘지는 게 보였다.", "shock"],
    ["assets/dc/dc-06.webp", "\"이건 좀 심하지 않냐.\"<br>\"형이 나한테 해준 조건인데.\"<br>형은 대답하지 못했다.", "q"],
    ["assets/situ/guy-17-night.webp", "한 시간이 걸렸다.<br>담배를 세 번 피우러 나갔다 왔고<br>결국 서른두 장에 전부 서명했다.", "win", "서명"],
    ["assets/lux-aquanaut.png", "인감을 꺼내는 형 손이 떨렸다.<br>스무 해 전 어머니 인감을 들고 나가던<br>그 손이었다."],
    ["assets/mc-38-lux-03.png", "10억을 넣었다.<br>형 회사는 그날부터<br>서류상 내 것이 됐다."],
    ["assets/situ/guy-17-gift.webp", "형이 나가면서 내 손을 잡았다.<br>\"고맙다. 역시 형제밖에 없다.\"<br>진심인 것 같았다.", "q"],
    ["assets/mc-38-lux-04.png", "그 말을 듣고<br>처음으로 속이 시원하지 않았다.<br>왜인지는 몰랐다."],
    ["assets/dc/dc-08.webp", "집에 와서 계약서를 다시 읽었다.<br>열두 쪽, 열아홉 쪽, 스물여섯 쪽.<br>다 내가 넣은 조항이었다."],
    ["assets/situ/guy-17-travel.webp", "형은 그 뒤로 나를 대표님이라고 불렀다.<br>회식 자리에서<br>남들 앞에서도 그랬다."],
    ["assets/liq-sake1.png", "\"형 그러지 마.\"<br>\"아니야. 이게 맞아.\"<br>형은 끝까지 그렇게 불렀다.", "q"],
    ["assets/mc-38-lux-05.png", "나는 이겼다고 생각했다.<br>여자도, 사람도, 물건도, 돈도, 형까지.<br>전부 뒤집었다."],
    ["assets/situ/guy-17-wed.webp", "그런데 형이 너무 쉽게 무너졌다.<br>전생에 나를 2주 만에 부순 사람이<br>계약서 한 장에 무릎을 꿇었다.", "shock"],
    ["assets/dc/dc-10.webp", "그게 이상했다.<br>이상한데 확인할 방법이 없어서<br>나는 그냥 넘어갔다."],
    ["assets/int-resolve.webp", "2015년. 스물일곱.<br>기사에 내 얼굴이 났다.<br>이 나라에서 제일 어린 부자라고.", "next", "NEXT"],
  ]
},
{
  no: "EP.08", title: "이 나라에서 제일 어린 부자",
  log: "전생에 나를 밟은 순서대로 전부 뒤집었다. 완벽했다. 그해 12월 회식 전까지는.",
  cuts: [
    ["assets/mc-38-lux-06.png", "2015년. 스물일곱. 자산 1조.<br>기사에 내 얼굴이 실렸다.<br>전생에 횡령 의혹을 냈던 그 신문사였다."],
    ["assets/story/champ-1.png", "사진 아래 문장이 이랬다.<br>'맨손으로 12년 만에.'<br>맨손이 아니었다. 나는 답을 갖고 시작했다."],
    ["assets/vip/star-m.webp", "인터뷰 요청이 하루에 스무 건씩 왔다.<br>비결이 뭐냐고 물었다.<br>\"운이 좋았습니다.\"라고 답했다.", "q"],
    ["assets/situ/guy-legend-1-travel.webp", "그 집안 회장은 내 이사회에 앉아 있었다.<br>안건에 반대한 적이 한 번도 없었다.<br>17%가 그런 거다."],
    ["assets/situ/guy-heir-night-2.webp", "나를 무너뜨렸어야 할 재무이사는<br>형 옆에서 장부를 쓰고 있었다.<br>사본은 매달 나한테 왔다."],
    ["assets/situ/girl-12-gift.webp", "나를 배신했어야 할 여자는<br>내 이름도 모른 채 잘 살았다.<br>아이가 둘이라고 들었다."],
    ["assets/situ/guy-17-night-2.webp", "형은 내 협력업체 사장이었다.<br>계약은 1년마다 갱신,<br>도장은 내가 찍었다."],
    ["assets/story/dept-1.png", "전생에 나를 밟았던 순서대로<br>네 명을 전부 뒤집었다.<br>완벽했다.", "win"],
    ["assets/car-rolls.png", "어머니를 큰 집으로 모셨다.<br>어머니는 방이 너무 많다고 했다.<br>나는 그 말이 좋았다."],
    ["assets/situ/girl-legend-1-travel.webp", "\"네가 형 잘 챙겨서 다행이다.\"<br>어머니는 여전히 그렇게 말했다.<br>나는 그냥 웃었다.", "q"],
    ["assets/story/yparty-1.png", "그해 12월 송년회를 크게 열었다.<br>계열사 대표 마흔 명.<br>형도 협력사 자격으로 왔다."],
    ["assets/liq-wine1.png", "형은 구석 테이블에 앉아 있었다.<br>내가 인사를 돌다가<br>마지막에 그 테이블에 갔다."],
    ["assets/situ/guy-17-night-3.webp", "형이 자리에서 일어나<br>두 손으로 잔을 받았다.<br>사람들이 다 보는 앞에서."],
    ["assets/mc-38-lux-07.png", "그리고 잔을 내려놓으면서<br>내 귀 쪽으로 몸을 기울였다.<br>목소리를 아주 낮췄다."],
    ["assets/situ/guy-17-night-4.webp", "\"너 2020년 3월 알지?\"<br>나는 잔을 든 채로 굳었다.<br>주변 소리가 한꺼번에 사라졌다.", "shock", "충격"],
    ["assets/dc/dc-11.webp", "2020년 3월.<br>코스피가 1439까지 빠지는 달.<br>이 세상에 그걸 아는 사람은 나뿐이어야 했다."],
    ["assets/situ/guy-17-night-5.webp", "형은 아무 일 없다는 듯<br>자리에 앉아 국을 떠먹었다.<br>나만 서 있었다."],
    ["assets/mc-38-lux-08.png", "그날 밤 나는 노트를 다시 폈다.<br>17년 동안 적은 것들.<br>전부 형도 알고 있다는 뜻이었다."],
    ["assets/int-resolve-2.webp", "말이 안 됐다.<br>형이 어떻게 아는가.<br>답은 하나뿐이었다.", "shock"],
    ["assets/int-resolve-3.webp", "형도 회귀자다.<br>그것도 나보다<br>먼저 온 회귀자.", "next", "NEXT"],
  ]
},
{
  no: "EP.09", title: "형도 회귀자였다",
  log: "\"나 말이야, 너보다 먼저 왔어.\" 내가 이긴 7년이 통째로 형의 계획이었다.",
  cuts: [
    ["assets/situ/guy-17-night-6.webp", "이틀 뒤 형이 내 사무실로 왔다.<br>약속도 없이 올라와서<br>소파에 먼저 앉았다."],
    ["assets/mc-38-lux-09.png", "\"물어볼 거 있어서 왔지?\"<br>형이 먼저 말을 꺼냈다.<br>나는 대답하지 않았다.", "q"],
    ["assets/situ/guy-14-date.webp", "\"나 말이야, 너보다 먼저 왔어.\"<br>형은 커피를 저으면서 말했다.<br>날씨 얘기하는 말투였다.", "q", "정체"],
    ["assets/dc/dc-13.webp", "\"2011년 옥상에서 떨어졌어.<br>너보다 15년 빨라.<br>그러니까 나는 세 번째 사는 중이야.\"", "q", "충격"],
    ["assets/situ/guy-14-sad.webp", "\"도장 바꿔치기, 잘하더라.<br>열여덟에 그 생각을 해?<br>나는 그때 진심으로 놀랐어.\"", "q"],
    ["assets/mc-38-lux-10.png", "형은 하나씩 짚었다.<br>부품업체 12%, 특허 출원일,<br>2008년 10월 매입 시작일까지."],
    ["assets/situ/guy-14-gift.webp", "\"다 봤어. 처음부터.<br>네가 노트 쓰는 것도 봤고<br>어디다 숨기는지도 알아.\"", "q", "shock"],
    ["assets/int-resolve-4.webp", "그럼 왜 안 막았느냐고 물었다.<br>내 목소리가 갈라졌다.<br>형은 그걸 듣고 웃었다."],
    ["assets/situ/guy-14-travel.webp", "\"막을 이유가 뭐 있어.<br>네가 키운 걸 뺏는 게<br>내가 키우는 것보다 싸잖아.\"", "q"],
    ["assets/dc/dc-15.webp", "그 말이 맞았다.<br>내가 12년을 걸려 만든 걸<br>형은 서류 한 장이면 가져간다."],
    ["assets/situ/guy-14-night.webp", "\"근데 왜 이제 말해?\"<br>\"이제 다 자랐으니까.\"<br>형은 잔을 내려놓고 일어섰다.", "q"],
    ["assets/mc-30s.webp", "7년을 이겼다고 생각했다.<br>그 7년이 통째로<br>형이 기다린 시간이었다.", "shock"],
    ["assets/situ/guy-14-wed.webp", "형이 문 앞에서 돌아봤다.<br>\"참, 계약서 열아홉 쪽 봤어?\"<br>나는 그 쪽을 외우고 있었다.", "q"],
    ["assets/dc/dc-17.webp", "열아홉 쪽은 내가 넣은 조항이었다.<br>경영권 분쟁이 생기면<br>지분을 액면가에 넘긴다는 내용."],
    ["assets/int-resolve-5.webp", "그건 형을 묶는 조항이었다.<br>내가 형한테 씌운 목줄이었다.<br>그런데 형이 그걸 왜 아나.", "shock"],
    ["assets/situ/guy-14-night-2.webp", "\"주어를 잘 봐.<br>거기 '투자자'라고 안 써 있고<br>'당사자'라고 써 있어.\"", "q", "함정"],
    ["assets/mc-male.webp", "나는 그날 밤 계약서를 다시 꺼냈다.<br>열아홉 쪽 세 번째 줄.<br>정말 '당사자'였다."],
    ["assets/dc/dc-19.webp", "변호사 셋이 두 달을 만진 문서였다.<br>그 셋 중 하나를<br>누가 소개했는지 나는 기억이 났다."],
    ["assets/situ/girl-heiress-night.webp", "그 집 딸이었다.<br>\"오빠는 왜 다 알고 있는 것처럼 굴어요?\"<br>그 눈빛의 값이 이제 왔다.", "shock"],
    ["assets/int-betrayal-5.webp", "내가 판 함정이었다.<br>내가 서명했다.<br>이번엔 위조도 아니었다.", "next", "NEXT"],
  ]
},
{
  no: "EP.10", title: "내가 판 함정에 내가 빠졌다",
  log: "전생엔 위조 계약서였다. 이번엔 내가 직접 서명한 진짜였다.",
  cuts: [
    ["assets/dc/dc-21.webp", "2016년 3월.<br>형이 임시주주총회 소집을 청구했다.<br>사유는 경영권 분쟁이었다."],
    ["assets/situ/guy-14-night-3.webp", "분쟁을 만든 건 형이었다.<br>만들기만 하면<br>열아홉 쪽이 자동으로 작동한다.", "shock"],
    ["assets/mc-rich.webp", "액면가 5천원.<br>내 지분 시가는 주당 41만원이었다.<br>82분의 1에 넘어간다."],
    ["assets/situ/girl-heiress-night-2.webp", "그 집 딸이 형 쪽에 섰다.<br>17%는 원래 내 것이었는데<br>그 집안이 되사간 뒤였다."],
    ["assets/vip/chaebol-f-2.webp", "\"오빠가 우리 집을 뺏었잖아요.\"<br>3년 동안 준비한 대답 같았다.<br>웃지 않고 말했다.", "q", "배신"],
    ["assets/situ/guy-legend-1-gift.webp", "회장은 아무 말도 하지 않았다.<br>이사회에서 딸 손을 들어줬다.<br>계산이 그쪽이 맞았을 뿐이다."],
    ["assets/dc/dc-23.webp", "주총은 40분 만에 끝났다.<br>열 살부터 15년을 쌓은 게<br>40분에 사라졌다.", "shock"],
    ["assets/situ/guy-14-night-4.webp", "형이 대표이사 자리에 앉았다.<br>내가 앉던 의자였다.<br>사진을 찍어 나한테 보냈다."],
    ["assets/mc-15.webp", "그걸로 안 끝났다.<br>2주 뒤에<br>배임 혐의로 고발이 들어왔다."],
    ["assets/situ/guy-heir-night-3.webp", "고발장에 붙은 자료가<br>내가 만든 장부였다.<br>재무이사가 준 걸로 되어 있었다.", "shock"],
    ["assets/dc/dc-25.webp", "그가 배신한 줄 알았다.<br>연락이 닿지 않았다.<br>나는 그를 저주하면서 구치소에 들어갔다."],
    ["assets/situ/girl-heiress-night-3.webp", "재판은 8개월이 걸렸다.<br>증인석에 그 집 딸이 앉았다.<br>나를 한 번도 쳐다보지 않았다."],
    ["assets/vip/poli-m.webp", "배임 480억.<br>1심 징역 2년.<br>항소는 하지 않았다.", "shock", "실형"],
    ["assets/situ/girl-legend-1-night-2.webp", "어머니가 면회를 왔다.<br>유리 너머에서 물었다.<br>\"너 정말 회삿돈 가져갔니?\"", "q"],
    ["assets/mc-16.webp", "아니라고 했다.<br>어머니는 고개를 끄덕였는데<br>눈이 나를 안 보고 있었다."],
    ["assets/situ/guy-14-night-5.webp", "형이 한 번 면회를 왔다.<br>손에 아무것도 안 들고 왔다.<br>10분을 앉아 있다가 일어섰다."],
    ["assets/situ/guy-14-night-6.webp", "\"고생해라.<br>회사는 형이 잘 지킬게.\"<br>그 말만 하고 갔다.", "q"],
    ["assets/int-rooftop-3.webp", "밤마다 천장을 봤다.<br>전생에도 이랬다.<br>다른 점은 이번엔 내가 서명했다는 것뿐."],
    ["assets/dc/dc-27.webp", "미래를 아는 게 무기라고 믿었다.<br>형도 아니까<br>그건 무기가 아니었다."],
    ["assets/int-rooftop-4.webp", "그런데 형이 모르는 게<br>딱 하나 있었다.<br>그걸 떠올리는 데 1년이 걸렸다.", "next", "NEXT"],
  ]
},
{
  no: "EP.11", title: "형이 모르는 게 하나 있다",
  log: "형은 전생의 기억을 믿는다. 회귀자의 약점은 미래가 아니라 과거다.",
  cuts: [
    ["assets/mc-17.webp", "형은 내가 아는 걸 전부 안다.<br>내가 뭘 살지, 언제 팔지,<br>어디로 도망갈지까지."],
    ["assets/dc/dc-29.webp", "그건 형이 두 번을 더 살았기 때문이다.<br>정보량으로는<br>내가 절대 못 이긴다."],
    ["assets/situ/guy-17-date.webp", "그런데 형이 아는 건<br>'전생에 일어난 일'이다.<br>이번 생에 새로 생긴 건 모른다.", "win"],
    ["assets/mc-18.webp", "이번 생에 내가 새로 만든 게 뭐가 있나.<br>1년을 세어봤다.<br>딱 하나 있었다."],
    ["assets/situ/guy-heir-night-4.webp", "2009년, 반지하 사무실에서 만난 회계사.<br>전생에 그는 2011년에<br>형한테 먼저 갔던 사람이다."],
    ["assets/situ/guy-heir-night-5.webp", "형의 기억 속에서<br>그는 처음부터 형의 사람이다.<br>2년 빠른 2009년은 형의 기억에 없다.", "win"],
    ["assets/lux-belt.png", "형은 그를 의심한 적이 한 번도 없다.<br>전생에 자기 편이었으니까.<br>그게 형의 유일한 빈틈이었다."],
    ["assets/situ/guy-heir-night-6.webp", "고발장에 그의 이름이 있었던 건<br>배신이 아니라<br>형이 그의 이름을 빌린 것이었다."],
    ["assets/story/champ-2.png", "그는 그 8개월 동안<br>형 옆자리에 그대로 앉아 있었다.<br>아무 일도 없다는 얼굴로."],
    ["assets/mc-young.webp", "나는 구치소에서 계산했다.<br>그가 앉아 있는 자리는<br>차명 계좌 47개가 지나가는 자리다.", "win"],
    ["assets/situ/guy-01-gift.webp", "형은 2010년부터 계좌를 만들었다.<br>내가 하나도 안 막은 이유가<br>이제야 쓸모가 생겼다."],
    ["assets/lux-bigbang.png", "10년치 자금 흐름.<br>액수가 아니라 흐름이 증거가 된다.<br>흐름은 사람이 있어야 읽는다."],
    ["assets/situ/guy-08-date.webp", "문제는 시점이었다.<br>지금 던지면<br>형은 회사 팔고 도망가면 그만이다."],
    ["assets/story/champ-3.png", "형을 완전히 끝내려면<br>도망갈 돈이 없어야 한다.<br>형이 전 재산을 한곳에 거는 날이 필요했다."],
    ["assets/situ/guy-08-gift.webp", "그런 날이 딱 하루 있다.<br>2020년 3월.<br>형은 그날 전 재산을 건다.", "win"],
    ["assets/situ/guy-01-night-2.webp", "형도 그날을 안다.<br>알기 때문에 반드시 베팅한다.<br>안다는 게 형을 그날로 끌고 간다.", "win", "역이용"],
    ["assets/story/clubkr-1.png", "형이 아는 건 바닥 날짜뿐이다.<br>거기까지 버티는 방법은<br>전생에 겪어본 적이 없다."],
    ["assets/situ/guy-08-night-2.webp", "전생에 형은 그 구간을<br>내 돈으로 버텼다.<br>이번엔 내 돈이 없다.", "win"],
    ["assets/int-rooftop-5.webp", "출소일은 2018년 1월.<br>2020년 3월까지<br>2년 2개월이 남아 있었다."],
    ["assets/story/clubkr-2.png", "나는 그 2년을<br>아무것도 안 하고 기다리기로 했다.<br>기다리는 건 자신 있었다.", "next", "NEXT"],
  ]
},
{
  no: "EP.12", title: "12년 전에 심어둔 사람",
  log: "출소 일주일 뒤, 12년째 형 옆에 앉아 있는 그 회계사가 나를 찾아왔다.",
  cuts: [
    ["assets/story/concert-1.png", "2018년 1월. 출소.<br>주머니에 5만원이 있었다.<br>마중 나온 사람은 없었다."],
    ["assets/situ/guy-08-night-3.webp", "집도, 회사도, 이름도 없었다.<br>형은 내가 끝났다고 믿었을 것이다.<br>실제로 끝나 보였다."],
    ["assets/story/concert-2.png", "고시원 한 달 33만원.<br>창문이 복도 쪽으로 났고<br>사람 지나가는 소리가 다 들렸다."],
    ["assets/situ/guy-08-night-4.webp", "일주일을 그 방에서 보냈다.<br>일곱 번째 날 저녁,<br>누가 문을 두드렸다."],
    ["assets/situ/guy-01-night-3.webp", "12년째 형 옆에 앉아 있는<br>그 회계사였다.<br>양복이 아니라 점퍼를 입고 있었다."],
    ["assets/situ/guy-08-night-5.webp", "\"고발장에 당신 이름이 있었습니다.\"<br>\"압니다. 제가 안 냈습니다.\"<br>그 말이 먼저였다.", "q"],
    ["assets/situ/guy-01-night-4.webp", "\"약속 지키러 왔습니다.<br>딱 한 번만 편들어달라고 하셨죠.\"<br>2009년에 쓴 각서를 꺼냈다.", "q", "회수"],
    ["assets/lux-birkin.png", "종이가 누렇게 변해 있었다.<br>내가 가진 한 장은<br>압수품으로 사라진 뒤였다."],
    ["assets/story/dept-2.png", "그가 가방에서<br>외장하드 하나를 꺼내 책상에 놨다.<br>\"12년치입니다.\"", "q"],
    ["assets/situ/guy-08-night-6.webp", "차명 계좌 47개.<br>2010년 첫 계좌부터<br>지난달 입금까지 전부.", "win"],
    ["assets/situ/guy-01-night-5.webp", "\"왜 지금까지 안 넘겼습니까.\"<br>\"넘길 자리가 없었습니다.<br>당신이 없었으니까.\"", "q"],
    ["assets/vip/hedge-m-2.webp", "그는 12년 동안<br>내가 준 돈을 한 푼도 안 썼다고 했다.<br>통장 하나를 같이 내밀었다."],
    ["assets/situ/guy-08-night.webp", "\"이건 제 돈이 아닙니다.\"<br>나는 그 돈으로<br>다시 시작할 수 있었다.", "q", "win"],
    ["assets/story/f1-1.png", "바로 검찰에 넘길 수도 있었다.<br>넘기면 형은 3년쯤 살고 나온다.<br>돈은 그대로 남는다."],
    ["assets/situ/guy-08-sad.webp", "그럼 의미가 없다.<br>형이 나한테 한 건<br>감옥이 아니라 삭제였으니까."],
    ["assets/situ/guy-01-night-6.webp", "형은 지금 잘나가고 있었다.<br>내 회사를 먹고,<br>그 집안과 손을 잡고."],
    ["assets/story/f1-2.png", "\"2년만 더 갖고 계십시오.\"<br>그가 물었다. \"왜 2년입니까.\"<br>나는 대답하지 않았다.", "q"],
    ["assets/situ/guy-08-travel.webp", "2020년 3월.<br>형이 전 재산을 거는 날.<br>그날까지 이건 종이일 뿐이다."],
    ["assets/situ/guy-01-night.webp", "그가 돌아가면서 한마디 했다.<br>\"저 이제 그만둬도 됩니까.\"<br>\"2년만 더 앉아 계세요.\"", "q"],
    ["assets/story/hanriver-1.png", "2020년 2월.<br>형이 보유 자산 전량을 담보로<br>레버리지를 최대로 당겼다.", "next", "NEXT"],
  ]
},
{
  no: "EP.13", title: "반대매매는 바닥보다 먼저 온다",
  log: "형의 판단은 맞았다. 3월 19일이 바닥이다. 문제는 거기까지 버티느냐였다.",
  cuts: [
    ["assets/story/hanriver-2.png", "2020년 2월. 형이 담보대출을 최대로 썼다.<br>회사 지분, 부동산, 그 집안 주식까지.<br>전부 한곳에 걸었다."],
    ["assets/situ/guy-01-sad.webp", "형의 판단은 맞았다.<br>3월 19일이 바닥이니까.<br>그건 나도 안다.", "win"],
    ["assets/situ/guy-08-wed.webp", "문제는 3월 19일까지<br>버틸 수 있느냐였다.<br>형은 그 구간을 겪어본 적이 없다."],
    ["assets/story/hyper-1.png", "담보 비율이 무너지면<br>증권사가 알아서 판다.<br>반대매매는 바닥보다 먼저 온다. 항상."],
    ["assets/situ/guy-01-travel.webp", "전생에 형은 이걸 안 겪었다.<br>그때는 내 회사가 있었고<br>내 돈으로 마진콜을 막았으니까."],
    ["assets/situ/guy-09-date.webp", "이번엔 내 돈이 없다.<br>내가 감옥에 있는 동안<br>형이 전부 가져갔으니까.", "win"],
    ["assets/story/hyper-2.png", "3월 9일. 첫 서킷브레이커.<br>형의 담보 비율이<br>유지 기준 아래로 내려갔다."],
    ["assets/situ/guy-01-wed.webp", "형이 돈을 구하러 다녔다.<br>그 집안에 먼저 갔다고 들었다.<br>회장은 만나주지 않았다.", "shock"],
    ["assets/vip/venture-m.webp", "3월 12일. 두 번째 서킷브레이커.<br>형은 그날 은행 세 곳을 돌았다.<br>전부 거절당했다."],
    ["assets/situ/guy-02-date.webp", "3월 16일 밤에<br>형이 나한테 전화를 걸었다.<br>2년 만이었다."],
    ["assets/situ/guy-09-gift.webp", "\"10억만 넣어줘.\"<br>2014년 국밥집에서 들은 문장이었다.<br>이번엔 지분 얘기가 없었다.", "q"],
    ["assets/situ/guy-02-gift.webp", "\"우리 사이에 계약서가 필요하냐.\"<br>내가 그렇게 물었다.<br>형은 아무 말도 못 했다.", "q", "역전"],
    ["assets/story/island-1.png", "3월 17일 오전 9시 3분.<br>강제청산이 들어갔다.<br>바닥까지 이틀 남은 시점이었다."],
    ["assets/situ/guy-09-night-2.webp", "나는 그 물량을 전부 받았다.<br>회계사가 12년 모은 돈과<br>내가 판 마지막 시계로.", "win", "인수"],
    ["assets/lux-datejust.png", "시계 하나가 800만원에 팔렸다.<br>어머니가 서른 살에 사준 것이었다.<br>그게 종잣돈이 됐다."],
    ["assets/story/island-2.png", "3월 19일. 코스피 1439.<br>형이 맞혔던 그 바닥이 왔다.<br>형은 그 자리에 없었다.", "win"],
    ["assets/situ/guy-02-night-2.webp", "형은 아는 게 많았지만<br>버티는 법은 몰랐다.<br>버텨본 적이 없어서."],
    ["assets/situ/guy-09-night-3.webp", "미래를 아는 사람이<br>미래에 못 가는 경우가 있다.<br>중간을 못 버티면 그렇게 된다."],
    ["assets/story/island-3.png", "4월에 지분 정리가 끝났다.<br>형이 갖고 있던 내 회사가<br>다시 내 이름으로 돌아왔다.", "win"],
    ["assets/story/space2-1.png", "그날 오후 그 집안 회장한테서<br>먼저 전화가 왔다.<br>\"오해가 있었던 것 같네.\"", "next", "NEXT"],
  ]
},
{
  no: "EP.14", title: "회장이 형을 버렸다",
  log: "회장이 딸을 데려왔다. 오해가 아니라 계산이었다. 이번 계산도 마찬가지고.",
  cuts: [
    ["assets/situ/guy-legend-1-night.webp", "회장이 만나자고 했다.<br>장소는 그쪽 사옥이 아니라<br>내 사무실이었다."],
    ["assets/vip/chaebol-m-2.webp", "\"오해가 있었던 것 같네.\"<br>오해가 아니었다. 계산이었다.<br>지금 이 자리도 계산이다.", "q"],
    ["assets/situ/guy-legend-1-night-2.webp", "2016년에 형 손을 들어준 것도,<br>2020년에 형을 버린 것도<br>같은 사람의 같은 계산이다."],
    ["assets/situ/guy-09-night-4.webp", "나는 그걸 탓하지 않았다.<br>탓해봐야 안 바뀐다.<br>대신 값을 매겼다."],
    ["assets/situ/girl-heiress-night-4.webp", "회장이 딸을 데려왔다.<br>2016년 증인석에 앉았던<br>그 사람이었다."],
    ["assets/vip/commo-f-2.webp", "\"그때는… 아버지가 시켜서.\"<br>나는 그 말을 믿지 않았다.<br>믿을 필요도 없었다.", "q"],
    ["assets/situ/girl-heiress-night-5.webp", "다만 그 여자가 가진 게 하나 있었다.<br>2016년에 형한테 넘어간<br>내 회사 지분 18%."],
    ["assets/story/space2-2.png", "형이 청산당하면서<br>그 18%가 그 집안으로 돌아가 있었다.<br>내가 마지막으로 회수할 것이었다."],
    ["assets/situ/guy-09-night-5.webp", "받았다. 시가의 절반에.<br>대신 각서를 썼다.<br>이번엔 서른두 장이 아니라 두 장.", "win"],
    ["assets/lux-tank.png", "두 장이면 충분했다.<br>긴 계약서는<br>속이려는 사람이 쓰는 것이다."],
    ["assets/situ/girl-heiress-night-6.webp", "그 여자가 나가면서 물었다.<br>\"오빠는 진짜 다 알고 있었어요?\"<br>\"이번엔 몰랐습니다.\"", "q"],
    ["assets/situ/guy-02-night-3.webp", "형은 그 사이<br>협력업체 등록을 신청해왔다.<br>2011년에 내가 열어준 그 자리였다."],
    ["assets/story/space2-3.png", "서류는 완벽했다.<br>단가도 낮췄고<br>납기도 줄였다."],
    ["assets/situ/guy-09-night-6.webp", "나는 반려했다.<br>사유란은 비워뒀다.<br>이번엔 밑에 두지 않았다.", "win"],
    ["assets/situ/guy-02-night-4.webp", "형이 사무실로 찾아왔다.<br>비서가 막았고<br>1층 로비에서 두 시간을 앉아 있었다."],
    ["assets/story/yparty-2.png", "CCTV로 봤다.<br>스무 해 전 현관에서<br>나를 보고 웃던 사람이었다."],
    ["assets/situ/guy-02-night-5.webp", "\"한 번만 만나자.\"<br>비서를 통해 전해온 말이었다.<br>나는 대답하지 않았다.", "q"],
    ["assets/situ/guy-09-night.webp", "만나면 흔들릴 것 같아서가 아니었다.<br>아직 하나가 남아 있었다.<br>어머니였다."],
    ["assets/story/yparty-3.png", "12년 동안 어머니는<br>내가 회삿돈을 들고 도망친 아들이었다.<br>1화에서 형이 한 말이 아직 살아 있었다."],
    ["assets/situ/guy-02-night-6.webp", "요양병원 주소를 받았다.<br>차로 두 시간이었다.<br>가는 데 12년이 걸렸다.", "next", "NEXT"],
  ]
},
{
  no: "EP.15", title: "어머니는 12년을 속았다",
  log: "증거는 있었다. 보여주면 어머니는 형을 잃는다. 스무 해를 아들이라 부른 사람이다.",
  cuts: [
    ["assets/situ/girl-legend-1-night-3.webp", "어머니는 3인실에 있었다.<br>창가 자리였고<br>침대 옆에 사진이 두 장 있었다."],
    ["assets/seed/aiyu.webp", "한 장은 내 초등학교 졸업식,<br>한 장은 형의 대학 입학식.<br>둘 다 액자에 들어 있었다."],
    ["assets/situ/girl-legend-1-night-4.webp", "어머니가 나를 한참 봤다.<br>알아보는 데 시간이 걸렸다.<br>\"너 살 많이 빠졌다.\"", "q"],
    ["assets/situ/guy-09-sad.webp", "12년 만이었다.<br>그동안 나는 감옥에 있었고<br>어머니는 그걸 당연하게 여겼다."],
    ["assets/situ/girl-legend-1-night-5.webp", "\"너… 이제 돈은 다 갚았니?\"<br>첫 질문이 그거였다.<br>나는 숨이 막혔다.", "q", "shock"],
    ["assets/seed/bong.webp", "어머니는 아직도<br>내가 회삿돈을 들고 도망쳤다고 안다.<br>2026년이 아니라 2016년 얘기다."],
    ["assets/situ/girl-legend-1-night-6.webp", "1화에서 형이 한 말이<br>12년을 살아서<br>이 병실까지 왔다."],
    ["assets/lux-boy.png", "가방 안에 외장하드가 있었다.<br>차명 계좌 47개, 12년치.<br>보여주면 끝나는 얘기였다."],
    ["assets/situ/guy-09-travel.webp", "손을 넣었다가 뺐다.<br>그걸 보여주면<br>어머니는 아들 하나를 잃는다."],
    ["assets/situ/girl-legend-1-date.webp", "스무 해를 아들이라 부른 사람이다.<br>내 앞에서가 아니라<br>어머니 앞에서 그랬다."],
    ["assets/seed/fake1.webp", "여든둘이었다.<br>남은 시간이 길지 않다는 걸<br>의사가 복도에서 말해줬다."],
    ["assets/situ/girl-legend-1-wed.webp", "\"엄마, 나 돈 다 갚았어.\"<br>거짓말을 했다.<br>갚을 돈이 애초에 없었다.", "q"],
    ["assets/situ/guy-09-wed.webp", "처음으로 이기는 게 싫었다.<br>이기려면<br>어머니한테 진실을 줘야 했다."],
    ["assets/situ/girl-legend-2-date.webp", "어머니가 내 손을 잡았다.<br>\"잘했다. 형한테도 고맙다고 해라.<br>형이 회사 잘 지켰다더라.\"", "q"],
    ["assets/seed/fake2.webp", "나는 고개를 끄덕였다.<br>목이 아파서<br>말을 못 했다."],
    ["assets/situ/girl-legend-2-gift.webp", "한 시간을 앉아 있었다.<br>어머니는 옛날 얘기를 했다.<br>대부분 형이 나온 얘기였다."],
    ["assets/situ/guy-10-date.webp", "나오는데 복도 끝에<br>사람이 서 있었다.<br>형이었다.", "shock"],
    ["assets/situ/guy-02-night.webp", "언제부터 있었는지 모른다.<br>문이 열려 있었으니까<br>다 들었을 것이다."],
    ["assets/seed/figure.webp", "형은 아무 말도 하지 않았다.<br>나도 하지 않았다.<br>지나쳐 갔다."],
    ["assets/situ/guy-02-sad.webp", "그리고 그 여름,<br>형이 나를 옥상으로 불렀다.<br>2026년 7월 15일이었다.", "next", "NEXT"],
  ]
},
{
  no: "EP.16", title: "이번엔 내가 난간 밖에 서 있지 않았다",
  log: "전생에 내가 서 있던 자리에 형이 서 있었다. 회귀자의 약점은 미래가 아니라 과거였다.",
  cuts: [
    ["assets/situ/guy-02-travel.webp", "2026년 7월 15일.<br>그 옥상이었다.<br>전생에 내가 떨어진 자리."],
    ["assets/situ/guy-02-wed.webp", "형이 난간 밖에 서 있었다.<br>등을 보이고,<br>비를 그대로 맞으면서."],
    ["assets/seed/hjin.webp", "\"올 줄 알았어.\"<br>형이 돌아보지 않고 말했다.<br>목소리가 젖어 있었다.", "q"],
    ["assets/situ/guy-03-date.webp", "\"나는 세 번 살았어.<br>세 번째도 너를 밟을 줄 알았지.<br>근데 왜 이번엔 안 됐는지 알아?\"", "q"],
    ["assets/situ/guy-10-gift.webp", "나는 안다.<br>1년을 감옥에서<br>그것만 생각했으니까."],
    ["assets/situ/guy-03-gift.webp", "2009년, 반지하 사무실.<br>형의 기억에 없는 2년.<br>거기서 갈렸다.", "win"],
    ["assets/seed/hson.webp", "형은 전생의 기억을 믿었다.<br>그 사람은 자기 편이라고.<br>12년 동안 한 번도 안 의심했다."],
    ["assets/situ/guy-10-night-2.webp", "회귀자의 약점은<br>미래를 아는 게 아니라<br>과거를 믿는 것이었다.", "win", "핵심"],
    ["assets/situ/guy-03-night-2.webp", "형이 웃었다.<br>\"그 회계사구나.\"<br>말투가 처음으로 흔들렸다.", "q"],
    ["assets/lux-bulgari.png", "\"미래를 아는 건 죄가 아니야.<br>근데 이건 죄야.\"<br>나는 외장하드를 꺼냈다.", "q"],
    ["assets/seed/sero.webp", "차명 계좌 47개.<br>2010년 첫 입금부터<br>지난달까지 12년치."],
    ["assets/situ/guy-03-night-3.webp", "형은 그걸 오래 봤다.<br>뺏으려고 하지 않았다.<br>이미 사본이 검찰에 있는 걸 알았을 것이다.", "win"],
    ["assets/vip/poli-m-2.webp", "수사는 넉 달 걸렸다.<br>형은 도망가지 않았다.<br>도망갈 돈이 2020년 3월에 사라졌으니까."],
    ["assets/situ/guy-03-night-4.webp", "구속영장 집행일에<br>형이 나를 한 번 봤다.<br>\"어머니한텐 뭐라고 할 거냐.\"", "q"],
    ["assets/situ/guy-10-night-3.webp", "\"형은 출장 갔다고 할게.\"<br>형이 처음으로<br>고맙다는 표정을 지었다.", "q"],
    ["assets/situ/girl-legend-2-night-2.webp", "어머니는 그해 겨울까지 사셨다.<br>끝까지 형이 해외에 있는 줄 알았다.<br>나는 매달 대신 편지를 썼다."],
    ["assets/seed/volley.webp", "회사는 상장했다.<br>2026년 가을,<br>전생에 무너진 그 계절에."],
    ["assets/situ/guy-03-night-5.webp", "재무이사 자리에 그가 앉았다.<br>17년 만에<br>진짜 자기 자리에 앉은 셈이다.", "win"],
    ["assets/situ/guy-03-night-6.webp", "나는 옥상에 자주 올라간다.<br>난간 안쪽에 서서<br>아래를 본다."],
    ["assets/situ/guy-03-night.webp", "이번 생에는<br>내가 난간 밖에<br>서 있지 않았다.", "gold", "완결"],
  ]
},
{
  no: "EP.17", title: "형이 남긴 상자",
  log: "형이 구치소에서 죽었다. 유품은 종이 상자 하나였고, 안에 노트가 세 권 있었다.",
  cuts: [
    ["assets/logos/logo-01.png", "2026년 10월. 상장했다.<br>전생에 무너진 그 계절에<br>종이 울렸다."],
    ["assets/situ/guy-18-travel.webp", "서른여덟. 다 되찾았다.<br>회사도, 이름도, 지분 60%도.<br>이번엔 계약서가 있었다."],
    ["assets/vip/star-f.webp", "기자가 물었다. \"형님은요?\"<br>\"출장 갔습니다.\"<br>나는 그 대답을 1년째 하고 있었다.", "q"],
    ["assets/situ/guy-12-sad.webp", "형은 서울구치소에 있었다.<br>1심 12년. 항소는 하지 않았다.<br>면회 신청을 세 번 냈고 세 번 다 거절당했다."],
    ["assets/situ/guy-18-sad.webp", "12월 4일 새벽에 전화가 왔다.<br>형이 죽었다고 했다.<br>심근경색이라고 했다.", "shock"],
    ["assets/liq-soju2.png", "그 자리에서 아무 말도 못 했다.<br>이겼는데 아무 소리도 안 났다.<br>술을 마셨는데 취하지 않았다."],
    ["assets/situ/guy-18-night.webp", "장례는 사흘이었다.<br>조문객이 열한 명 왔고<br>그중 아홉은 내 회사 직원이었다."],
    ["assets/lux-suit.png", "유품은 종이 상자 하나였다.<br>교도관이 건네면서 말했다.<br>\"동생분 앞으로 남기신 겁니다.\"", "q"],
    ["assets/situ/guy-18-gift.webp", "상자를 두 달 동안 열지 않았다.<br>열면 뭔가 무너질 것 같았다.<br>실제로 그랬다."],
    ["assets/situ/guy-18-date.webp", "2027년 2월에 상자를 열었다.<br>안에 노트가 세 권 있었다.<br>형 필체였다."],
    ["assets/logos/logo-02.png", "표지에 숫자가 하나씩 적혀 있었다.<br>1, 2, 3.<br>무슨 뜻인지는 첫 장에서 알았다."],
    ["assets/situ/guy-12-date.webp", "1번 노트 첫 줄.<br>'첫 번째 생. 나는 마흔한 살에 죽었다.'<br>형이 쓴 글이었다.", "shock"],
    ["assets/situ/guy-12-gift.webp", "형이 회귀자라는 건 9화에서 들었다.<br>세 번 살았다는 것도 들었다.<br>그런데 순서가 달랐다."],
    ["assets/situ/guy-12-travel.webp", "형은 자기가 먼저 죽는다고 썼다.<br>나보다 먼저.<br>매번 그랬다고 썼다."],
    ["assets/lux-daytona.png", "2번 노트에는 날짜 하나가 반복됐다.<br>2026년 7월 15일.<br>열일곱 번 적혀 있었다.", "shock"],
    ["assets/situ/guy-12-night.webp", "그건 내가 옥상에서 떨어진 날이다.<br>1화의 그날.<br>형이 왜 그 날짜를 열일곱 번 썼나."],
    ["assets/situ/guy-18-wed.webp", "3번 노트는 절반이 백지였다.<br>마지막으로 쓴 글자가<br>2016년 3월이었다."],
    ["assets/situ/guy-12-wed.webp", "2016년 3월.<br>형이 나를 감옥에 보낸 달이다.<br>거기서 펜이 멈춰 있었다."],
    ["assets/situ/guy-18-night-2.webp", "사흘을 안 잤다.<br>세 권을 처음부터 다시 읽었다.<br>이번엔 순서대로."],
    ["assets/logos/glogo-g2.png", "다 읽고 나서 알았다.<br>형은 나를 밟은 게 아니었다.<br>형은 나를 끌어내린 거였다.", "next", "NEXT"],
  ]
},
{
  no: "EP.18", title: "세 번 다 같은 날이었다",
  log: "1번 노트, 2번 노트, 3번 노트. 전부 2026년 7월 15일에서 끝났다.",
  cuts: [
    ["assets/situ/guy-19-date.webp", "1번 노트. 첫 번째 생.<br>형이 아는 세상에서<br>나는 서른여덟에 옥상에서 떨어졌다."],
    ["assets/situ/guy-12-night-2.webp", "형은 그때 사채에 쫓기고 있었다.<br>내 장례식에 오지 못했고<br>3년 뒤 마흔하나에 죽었다."],
    ["assets/lux-diamond.png", "'동생이 죽고 나서 알았다.<br>회삿돈을 들고 도망친 게 아니었다.<br>누가 그렇게 만든 거였다.'", "q"],
    ["assets/situ/guy-19-sad.webp", "형은 그 문장을 쓰고<br>다음 장에 회사 로고를 하나 그려놨다.<br>서툴게 그린 그림이었다."],
    ["assets/logos/glogo-g3.png", "그 로고를 나는 안다.<br>6화에서 내가 17%를 들이민 그 그룹.<br>10화에서 나를 감옥에 보낸 그 집안."],
    ["assets/situ/guy-13-date.webp", "2번 노트. 두 번째 생.<br>형은 회귀했고, 이번엔 나를 도왔다.<br>그렇게 적혀 있었다.", "shock"],
    ["assets/situ/guy-13-gift.webp", "'동생 회사에 내 이름을 안 올렸다.<br>지분도 안 받았다.<br>뒤에서만 밀어줬다.'", "q"],
    ["assets/car-benzs.png", "그 생에서 나는 더 크게 됐다.<br>서른다섯에 자산 2조.<br>형은 운전기사로 옆에 있었다."],
    ["assets/situ/guy-13-travel.webp", "'잘될수록 무서웠다.<br>날짜가 다가오고 있었으니까.'<br>형은 그렇게 썼다.", "q"],
    ["assets/lux-gmt.png", "2026년 7월 15일.<br>두 번째 생에서도 나는 죽었다.<br>이번엔 투신이 아니라 교통사고였다.", "shock"],
    ["assets/situ/guy-13-night.webp", "'방식은 매번 달랐다.<br>날짜만 같았다.'<br>형은 그 줄에 밑줄을 세 번 그었다.", "q"],
    ["assets/situ/guy-19-night.webp", "우연이 아니라는 뜻이다.<br>사고가 아니라는 뜻이다.<br>누가 그날을 정해놓고 있다는 뜻이다.", "shock"],
    ["assets/situ/guy-13-wed.webp", "3번 노트. 세 번째 생.<br>첫 장에 계획이 적혀 있었다.<br>'이번엔 반대로 한다.'"],
    ["assets/situ/guy-13-sad.webp", "'두 번을 지켜서 두 번 다 죽었다.<br>가진 게 많을수록 그날 그 자리에 간다.<br>그럼 다 뺏으면 된다.'", "q", "반전"],
    ["assets/situ/guy-19-gift.webp", "나는 그 문장을 열 번쯤 다시 읽었다.<br>다 뺏으면 된다.<br>그게 1화였다."],
    ["assets/lux-fur.png", "위조 각서도, 약혼녀의 거짓말도,<br>새벽 4시의 잠적 메일도<br>같은 계획의 부품이었다."],
    ["assets/situ/guy-13-night-2.webp", "'회사가 없으면 상장도 없다.<br>상장이 없으면 그날 그 옥상에<br>올라갈 일이 없다.'", "q"],
    ["assets/situ/guy-19-travel.webp", "형의 계산은 틀리지 않았다.<br>다만 하나를 못 봤다.<br>다 잃은 사람도 옥상에 올라간다는 것."],
    ["assets/situ/guy-13-night-3.webp", "'2026년 7월 15일.<br>동생이 옥상에 올라갔다는 연락을 받았다.<br>내가 또 실패했다.'", "q", "shock"],
    ["assets/situ/guy-19-wed.webp", "그리고 노트는 2016년 3월에서 끊긴다.<br>순서가 안 맞는다.<br>2026년 일을 어떻게 미리 썼나.", "next", "NEXT"],
  ]
},
{
  no: "EP.19", title: "형은 나를 살리려고 밟았다",
  log: "3번 노트의 마지막 장은 뒤에서부터 쓴 것이었다. 형은 네 번째를 준비하고 있었다.",
  cuts: [
    ["assets/situ/guy-20-date.webp", "노트를 뒤집었다.<br>3번 노트는 뒤에서부터도 쓰여 있었다.<br>글씨가 훨씬 흐렸다."],
    ["assets/situ/guy-13-night-4.webp", "구치소에서 쓴 것이었다.<br>날짜가 2026년 8월부터<br>죽기 사흘 전까지 이어졌다."],
    ["assets/seed/writer.webp", "'동생이 살았다.<br>옥상에서 떨어졌는데 살았다.<br>나는 그게 무슨 뜻인지 안다.'", "q"],
    ["assets/situ/guy-20-sad.webp", "형은 내가 회귀한 걸 알고 있었다.<br>죽지 않고 되돌아갔다는 걸.<br>세 번을 살아본 사람은 그걸 안다."],
    ["assets/situ/guy-13-night-5.webp", "'그러면 이번 생은 네 번째다.<br>동생한테는 두 번째고.<br>나한테는 마지막이다.'", "q"],
    ["assets/situ/guy-20-gift.webp", "그래서 형은 9화에서<br>자기 정체를 먼저 밝혔던 것이다.<br>내가 알아야 대비하니까."],
    ["assets/situ/guy-11-date.webp", "그래서 회계사를 12년 동안<br>한 번도 안 건드렸던 것이다.<br>모르는 척한 게 아니라 남겨둔 것이었다.", "shock"],
    ["assets/situ/guy-20-travel.webp", "9화에서 형이 열아홉 쪽을 알려준 것도,<br>10화에서 나를 감옥에 보낸 것도<br>같은 이유였다."],
    ["assets/situ/guy-13-night-6.webp", "'2020년 3월에 동생이 밖에 있으면<br>전 재산을 건다. 그러다 죽는다.<br>2년만 안에 있으면 그 구간을 건너뛴다.'", "q", "반전"],
    ["assets/situ/guy-20-night.webp", "배임 480억, 징역 2년.<br>그건 형벌이 아니라<br>형이 나한테 씌운 방공호였다."],
    ["assets/lux-goyard.png", "12화에서 회계사가<br>내 돈을 한 푼도 안 쓰고 12년을 기다린 것도<br>형이 시킨 일이었다."],
    ["assets/situ/guy-11-gift.webp", "'출소하면 동생한테 가라.<br>내 얘기는 하지 마라.<br>미워해야 살아남는다.'", "q", "shock"],
    ["assets/situ/guy-20-night-2.webp", "13화의 반대매매도 그렇다.<br>형은 2020년 3월을 세 번 겪었다.<br>버티는 법을 모를 리가 없다."],
    ["assets/situ/guy-03-sad.webp", "형은 일부러 청산당했다.<br>자기 돈을 전부 내 앞에 흘려놓고<br>그걸로 내가 회사를 되찾게 했다.", "shock"],
    ["assets/situ/guy-03-travel.webp", "14화에서 형이 로비에 두 시간 앉아 있던 것도,<br>15화에서 병실 복도에 서 있던 것도<br>부탁하러 온 게 아니었다."],
    ["assets/situ/guy-11-travel.webp", "'한 번만 보고 싶었다.<br>말은 안 하는 게 낫다.<br>고마워하면 다시 옥상에 간다.'", "q"],
    ["assets/situ/guy-20-wed.webp", "16화에서 형이 난간 밖에 서 있던 건<br>도망친 게 아니었다.<br>내가 그 자리에 못 서게 먼저 선 것이었다.", "shock"],
    ["assets/situ/guy-11-sad.webp", "\"어머니한텐 뭐라고 할 거냐.\"<br>그게 형의 마지막 말이었다.<br>나는 그걸 항복으로 들었다.", "q"],
    ["assets/situ/guy-20-night-3.webp", "2027년 2월, 나는 상자를 앞에 두고<br>1년 만에 형을 미워하는 걸 그만뒀다.<br>그만두는 데 사흘이 걸렸다."],
    ["assets/situ/guy-03-wed.webp", "노트 맨 뒷장에 한 줄이 더 있었다.<br>'동생아, 그날 그 자리에 있던 사람을 찾아라.'<br>이름은 적혀 있지 않았다.", "next", "NEXT"],
  ]
},
{
  no: "EP.20", title: "그럼 누가 나를 죽였나",
  log: "세 번 다 방식이 달랐고 날짜는 같았다. 사고가 세 번 반복되면 그건 사고가 아니다.",
  cuts: [
    ["assets/situ/guy-21-date.webp", "형이 죽은 뒤 나는 노트를 다시 정리했다.<br>세 번의 생, 세 번의 죽음.<br>공통점을 뽑았다."],
    ["assets/logos/glogo-g5.png", "첫 번째 생: 배신 뒤 투신.<br>두 번째 생: 교통사고.<br>세 번째 생: 상장 두 달 전 각서."],
    ["assets/situ/guy-21-sad.webp", "방식이 전부 다르다.<br>다른데 날짜만 같다.<br>사람이 하는 일이라는 뜻이다.", "shock"],
    ["assets/lux-kelly.png", "형은 두 번째 생에서<br>내 옆에 운전기사로 붙어 있었다.<br>그런데도 못 막았다."],
    ["assets/situ/guy-21-gift.webp", "붙어 있는데 못 막았다는 건<br>범인이 밖에 있는 사람이 아니라<br>안에 있는 사람이라는 뜻이다."],
    ["assets/vip/hedge-f.webp", "내 주변에서 세 번의 생에<br>전부 등장한 사람을 세어봤다.<br>넷이 남았다."],
    ["assets/situ/guy-11-night.webp", "회계사. 두 번째 생에는 없었다.<br>형이 처음 그를 찾아간 게 세 번째 생이니까.<br>지웠다."],
    ["assets/fmc-22.webp", "약혼녀. 이번 생에는 나를 만난 적도 없다.<br>3화에서 부도를 막았으니까.<br>지웠다."],
    ["assets/situ/guy-legend-2-date.webp", "그 집안 회장.<br>세 번 다 있었다.<br>다만 회장은 늘 늦게 나타났다."],
    ["assets/situ/girl-13-date.webp", "그리고 그 집 딸.<br>세 번 다 있었다.<br>그리고 매번 먼저 나타났다.", "shock"],
    ["assets/situ/guy-21-travel.webp", "첫 번째 생에서<br>내 회사를 인수하러 온 사람이<br>회장이 아니라 그 여자였다."],
    ["assets/situ/girl-13-sad.webp", "두 번째 생에서<br>내 차에 마지막으로 탔던 손님이<br>그 여자였다고 형은 적었다.", "shock"],
    ["assets/situ/guy-21-night.webp", "세 번째 생에서는<br>10화 증인석에 앉았고<br>14화에서 사과하러 왔다."],
    ["assets/situ/girl-13-gift.webp", "6화에서 그 여자가 한 말.<br>\"오빠는 왜 다 알고 있는 것처럼 굴어요?\"<br>나는 그걸 감탄으로 들었다.", "q"],
    ["assets/situ/guy-21-wed.webp", "다시 들어보면 그건 감탄이 아니다.<br>확인이다.<br>내가 뭘 아는지 재고 있었던 것이다.", "shock"],
    ["assets/situ/girl-13-travel.webp", "그 여자가 스물여섯에<br>후계자 수업 중이라며 협상 자리에 나온 것도<br>우연이 아니었다."],
    ["assets/lux-lady.png", "회장은 나를 몰랐다.<br>그 여자가 나를 알았다.<br>순서가 그렇다."],
    ["assets/situ/guy-21-night-2.webp", "문제는 근거였다.<br>세 번의 생을 근거로 삼을 수는 없다.<br>법정에서 노트는 소설이다."],
    ["assets/situ/girl-13-night.webp", "그래서 다른 걸 물었다.<br>회귀자도 아닌 사람이<br>어떻게 매번 나보다 먼저 움직였나."],
    ["assets/situ/guy-04-date.webp", "답은 하나뿐이었다.<br>그 여자는 내 계획을 읽고 있었다.<br>어딘가에 적힌 걸 보고서.", "next", "NEXT"],
  ]
},
{
  no: "EP.21", title: "내 노트가 어떻게 새어나갔나",
  log: "열 살에 쓰기 시작한 노트. 그걸 본 사람은 세상에 셋뿐이었다.",
  cuts: [
    ["assets/situ/guy-22-date.webp", "2화에서 나는 노트를 쓰기 시작했다.<br>전생의 12년을 날짜까지 적은 노트.<br>열 살부터 스물다섯까지 썼다."],
    ["assets/logos/glogo-g6.png", "그 안에 다 있다.<br>도장, 부도일, 특허 출원, 리먼, 2020년 3월.<br>내가 한 일의 순서가 전부."],
    ["assets/situ/guy-22-sad.webp", "그 노트를 본 사람은 셋이다.<br>형, 회계사, 그리고 어머니.<br>다른 사람에게는 보인 적이 없다."],
    ["assets/situ/guy-04-gift.webp", "형은 9화에서 직접 말했다.<br>\"네가 노트 쓰는 것도 봤고<br>어디다 숨기는지도 알아.\"", "q"],
    ["assets/situ/guy-22-gift.webp", "형이 유출했다면<br>3번 노트를 나한테 남길 이유가 없다.<br>형은 뺀다."],
    ["assets/situ/guy-11-wed.webp", "회계사는 12년 동안<br>내가 준 돈을 한 푼도 쓰지 않았다.<br>통장을 그대로 내밀었던 사람이다."],
    ["assets/situ/guy-11-night-2.webp", "그가 유출했다면<br>2018년 고시원 문을 두드릴 이유가 없다.<br>그도 뺀다."],
    ["assets/situ/girl-legend-2-sad.webp", "남은 건 하나였다.<br>나는 그 이름을 지우려고<br>이틀을 다른 사람을 찾았다.", "shock"],
    ["assets/situ/guy-22-travel.webp", "15화에서 어머니가 한 말을 다시 떠올렸다.<br>\"잘했다. 형한테도 고맙다고 해라.<br>형이 회사 잘 지켰다더라.\"", "q"],
    ["assets/situ/girl-legend-2-night.webp", "형은 그때 협력업체에서 반려당한 사람이었다.<br>회사를 지킨 사람이 아니었다.<br>어머니는 그걸 어디서 들었나."],
    ["assets/situ/guy-22-night.webp", "면회도 못 오고, 전화도 안 되고,<br>요양병원 3인실에 12년 누워 있던 사람이<br>회사 상황을 알고 있었다.", "shock"],
    ["assets/situ/girl-legend-2-travel.webp", "누가 어머니를 찾아가고 있었다.<br>12년 동안.<br>내가 감옥에 있는 동안에도."],
    ["assets/car-morning.png", "요양병원 면회 기록을 뗐다.<br>2016년부터 2026년까지<br>같은 이름이 마흔한 번 있었다.", "shock"],
    ["assets/situ/girl-13-night-2.webp", "그 집 딸이었다.<br>내가 감옥에 있는 동안<br>내 어머니를 마흔한 번 만났다.", "shock", "막장"],
    ["assets/situ/guy-22-wed.webp", "간병인한테 물었다.<br>\"손녀분인 줄 알았어요.<br>어머님이 제일 반기셨는데.\"", "q"],
    ["assets/situ/girl-legend-2-wed.webp", "어머니는 그 여자한테 옛날 얘기를 했을 것이다.<br>15화에서 나한테 한 것처럼.<br>한 시간씩, 마흔한 번."],
    ["assets/lux-lovebr.png", "그 얘기 속에는<br>열여덟에 인감을 바꾼 아들이 있고<br>스무 살에 3천으로 회사를 산 아들이 있다."],
    ["assets/situ/guy-22-night-2.webp", "노트를 통째로 넘길 필요도 없었다.<br>어머니 입으로 충분했다.<br>어머니는 그게 자랑인 줄 알았다."],
    ["assets/situ/girl-13-wed.webp", "그런데 그건 2016년부터다.<br>그 여자는 2013년 협상 자리에서<br>이미 나를 재고 있었다."],
    ["assets/situ/girl-legend-2-night-3.webp", "2013년 이전에도<br>어머니를 만난 사람이 있어야 한다.<br>면회 기록 이전의 기록을 찾았다.", "next", "NEXT"],
  ]
},
{
  no: "EP.22", title: "1998년에 이미 시작돼 있었다",
  log: "형은 아버지 친구의 아들이 아니었다. 그 집안이 우리 집에 넣은 아이였다.",
  cuts: [
    ["assets/situ/guy-04-night-2.webp", "아버지 공장 서류를 다 뒤졌다.<br>1997년 것부터.<br>창고에 열여덟 상자가 있었다."],
    ["assets/logos/glogo-g7.png", "1998년 3월 자금 조달 내역.<br>부도 직전에 6억이 들어와 있었다.<br>차입처 이름이 비어 있었다."],
    ["assets/situ/guy-04-sad.webp", "그 6억이 없었으면<br>우리 집은 1998년에 끝났다.<br>나는 그 돈 얘기를 들은 적이 없다.", "shock"],
    ["assets/vip/venture-f.webp", "당시 경리부장을 찾아갔다.<br>여든두 살이었고<br>세 번째 방문에서 입을 열었다."],
    ["assets/situ/guy-04-night-3.webp", "\"그 돈은 조건이 있었습니다.\"<br>\"무슨 조건입니까.\"<br>\"아이를 하나 받으라고 했습니다.\"", "q", "충격"],
    ["assets/situ/guy-04-night-4.webp", "형이었다.<br>아버지 친구의 아들도 아니고<br>사고로 부모를 잃은 아이도 아니었다."],
    ["assets/situ/guy-legend-2-sad.webp", "그 집안이 우리 집에 넣은 아이였다.<br>1998년 5월.<br>내가 회귀한 그 두 달 뒤였다.", "shock"],
    ["assets/situ/girl-legend-2-night-4.webp", "어머니는 알고 받았다.<br>공장을 살리는 조건이었으니까.<br>그래서 스무 해를 아들이라 불렀다."],
    ["assets/lux-marmont.png", "\"오늘부터 네 형이다.\"<br>1화에서 어머니가 사흘 만에 한 말.<br>사흘이 아니라 계약이었다.", "q"],
    ["assets/situ/guy-04-travel.webp", "그럼 형이 왜 그 집안을 배신했나.<br>답은 형 노트 1번에 있었다.<br>첫 번째 생 마지막 장."],
    ["assets/situ/guy-04-night-5.webp", "'동생 장례식에 못 갔다.<br>그 집 사람들이 나를 잡아뒀다.<br>그때 알았다. 나는 도구였다.'", "q"],
    ["assets/situ/guy-04-night.webp", "형은 우리 집을 감시하러 들어온 아이였다.<br>내가 무엇을 하는지 보고하는 자리.<br>그게 스무 해였다."],
    ["assets/situ/guy-04-night-6.webp", "9화에서 형이 한 말이 다시 들렸다.<br>\"다 봤어. 처음부터.\"<br>그건 자랑이 아니라 자백이었다.", "q", "shock"],
    ["assets/situ/guy-04-wed.webp", "그 집안은 회귀자가 아니다.<br>회귀자가 필요 없었다.<br>스무 해 동안 옆에 사람을 두면 된다."],
    ["assets/situ/girl-13-night-3.webp", "그 집 딸이 나보다 먼저 움직인 이유가<br>이제야 맞아떨어졌다.<br>보고서를 받고 있었으니까."],
    ["assets/situ/guy-05-night-2.webp", "형은 세 번째 생에서<br>보고를 끊었다.<br>끊은 대신 나를 먼저 무너뜨렸다."],
    ["assets/situ/guy-05-night-3.webp", "그 집안이 손대기 전에<br>가진 걸 전부 빼앗으면<br>표적에서 빠진다고 봤던 것이다.", "shock"],
    ["assets/situ/guy-05-night-4.webp", "형이 나한테 뒤집어씌운 횡령도,<br>회사 전체에 돌린 새벽 4시 메일도<br>그 집안 눈앞에서 벌인 연극이었다."],
    ["assets/lux-nautilus.png", "형은 20년치 배신을<br>2주에 압축해서 내 앞에 쏟았다.<br>믿게 하려면 그래야 했으니까."],
    ["assets/situ/guy-legend-2-gift.webp", "이제 남은 건 하나다.<br>그 집안이 왜 하필<br>7월 15일이어야 했는가.", "next", "NEXT"],
  ]
},
{
  no: "EP.23", title: "7월 15일은 우리 집 날짜였다",
  log: "그 집안이 고른 날짜가 아니었다. 아버지가 죽은 날이었다.",
  cuts: [
    ["assets/situ/guy-06-date.webp", "7월 15일.<br>세 번의 생에서 반복된 그 날짜를<br>나는 회사 달력에서만 찾고 있었다."],
    ["assets/situ/girl-legend-2-night-5.webp", "그런데 그건 회사 날짜가 아니었다.<br>어머니 병실 사진 뒷면에<br>같은 날짜가 적혀 있었다."],
    ["assets/situ/guy-06-sad.webp", "1998년 7월 15일.<br>아버지가 공장에서 쓰러진 날.<br>내가 회귀하고 넉 달 뒤였다.", "shock"],
    ["assets/logos/glogo-g8.png", "그날 아버지는 6억의 조건을<br>다시 협상하러 갔다.<br>형을 돌려보내겠다고 했다고 한다."],
    ["assets/situ/guy-legend-2-travel.webp", "돌아오지 못했다.<br>사인은 심근경색이었다.<br>형이 죽은 것과 같은 사인이었다.", "shock", "막장"],
    ["assets/situ/guy-06-gift.webp", "그 집안은 날짜를 고른 게 아니었다.<br>한 번 통한 방식을<br>세 번 더 쓴 것뿐이었다."],
    ["assets/situ/girl-13-night-4.webp", "그 여자한테 연락했다.<br>2027년 3월.<br>7년 만의 통화였다."],
    ["assets/situ/girl-13-night-5.webp", "\"어머니 자주 뵀다면서요.\"<br>3초쯤 조용했다.<br>\"좋은 분이셨어요.\"", "q"],
    ["assets/situ/guy-06-travel.webp", "부인하지 않았다.<br>부인할 필요가 없는 사람은<br>이미 이겼다고 믿는 사람이다."],
    ["assets/situ/girl-05-date.webp", "\"오빠, 그거 아세요?<br>저희 집은 사람을 안 죽여요.<br>그냥 그 사람이 갈 자리를 만들 뿐이에요.\"", "q", "shock"],
    ["assets/lux-neverfull.png", "1998년 아버지에게는 6억을,<br>2016년 나에게는 열아홉 쪽을,<br>2026년 형에게는 12년을 만들어줬다."],
    ["assets/situ/guy-06-night.webp", "손에 피를 안 묻히는 집안이다.<br>그래서 증거가 없다.<br>세 번의 생을 겪어도 없다."],
    ["assets/situ/guy-11-night-3.webp", "회계사한테 갔다.<br>이번엔 12년치가 아니라<br>1998년치를 물었다."],
    ["assets/situ/guy-11-night-4.webp", "\"그 6억 말입니다.<br>형 명의로 나간 겁니까,<br>그 집안 명의로 나간 겁니까.\"", "q"],
    ["assets/situ/guy-11-night-5.webp", "그가 사흘 뒤에 봉투를 들고 왔다.<br>\"둘 다 아닙니다.<br>어머님 명의로 나갔습니다.\"", "q", "shock"],
    ["assets/situ/girl-legend-2-night-6.webp", "어머니는 1998년에<br>그 집안 돈을 자기 이름으로 받았다.<br>29년째 상환 중이었다."],
    ["assets/situ/guy-06-wed.webp", "매달 얼마씩 나갔는지 봤다.<br>내가 감옥에 있던 2년에도<br>한 달도 안 밀렸다."],
    ["assets/situ/guy-06-night-2.webp", "그 돈을 누가 냈나.<br>형이었다.<br>협력업체 사장으로 벌던 돈이었다.", "shock"],
    ["assets/liq-wh2.png", "형은 감시하러 들어온 아이였고,<br>내 어머니 빚을 29년 갚은 사람이었다.<br>둘 다 사실이었다."],
    ["assets/situ/guy-06-night-3.webp", "차명 계좌 47개.<br>그중 열한 개가 어디로 갔는지<br>이제야 보였다.", "next", "NEXT"],
  ]
},
{
  no: "EP.24", title: "네 번째 여름은 없다",
  log: "2027년 7월 15일. 나는 그 옥상에 다시 올라갔다. 이번엔 난간 밖에 아무도 없었다.",
  cuts: [
    ["assets/situ/guy-07-date.webp", "2027년 4월.<br>나는 세 가지를 가지고 있었다.<br>노트 세 권, 봉투 하나, 계좌 47개."],
    ["assets/situ/guy-11-night-6.webp", "노트는 법정에서 소설이다.<br>계좌는 형의 죄다.<br>쓸 수 있는 건 봉투 하나였다."],
    ["assets/lux-prada.png", "1998년 6억.<br>어머니 명의, 29년 상환.<br>이자율이 연 34%였다.", "shock"],
    ["assets/vip/poli-f.webp", "그 시절에도 불법이었다.<br>29년을 받아 갔으니<br>공소시효가 끊긴 적이 없다.", "win"],
    ["assets/situ/guy-07-sad.webp", "회사 하나를 무너뜨리는 데는<br>큰 게 필요 없다.<br>끊기지 않은 작은 게 하나면 된다."],
    ["assets/situ/guy-legend-2-night.webp", "회장이 먼저 연락해왔다.<br>세 번째였다.<br>이번에도 첫 마디가 같았다.", "q"],
    ["assets/situ/guy-legend-2-night-2.webp", "\"오해가 있었던 것 같네.\"<br>\"세 번째 오해십니다.\"<br>그 뒤로는 아무 말도 안 나왔다.", "q", "역전"],
    ["assets/situ/girl-13-night-6.webp", "그 여자가 따로 찾아왔다.<br>이번엔 사과하러 온 게 아니었다.<br>거래하러 왔다."],
    ["assets/situ/girl-heiress-wed.webp", "\"저희 집 지분 다 드릴게요.<br>대신 아버지는 빼주세요.\"<br>14화에서 내가 한 짓을 그대로 따라 했다.", "q"],
    ["assets/situ/guy-07-gift.webp", "받지 않았다.<br>받으면 또 두 장짜리 각서를 쓰게 되고<br>그럼 네 번째 여름이 온다."],
    ["assets/vip/poli-f-2.webp", "2027년 6월. 기소.<br>회장은 구속됐고<br>그 여자는 불구속으로 재판을 받았다.", "win"],
    ["assets/logos/logo-04.png", "그 집안 계열사가 하나씩 떨어져 나갔다.<br>나는 하나도 사지 않았다.<br>사면 그 집안이 내 안으로 들어온다."],
    ["assets/situ/guy-07-travel.webp", "형의 47개 계좌는<br>내가 검찰에 냈다.<br>죽은 사람 죄까지 덮지는 않았다."],
    ["assets/situ/guy-07-night.webp", "대신 열한 개는 따로 표시했다.<br>어머니 빚을 갚은 돈이라고<br>의견서에 썼다."],
    ["assets/girl-legend-2.png", "어머니 무덤에는<br>아무 말도 하지 않았다.<br>알려주는 게 이기는 거였는데 안 했다."],
    ["assets/situ/guy-07-wed.webp", "2027년 7월 15일.<br>나는 그 옥상에 올라갔다.<br>이번엔 아무도 난간 밖에 없었다.", "win"],
    ["assets/situ/guy-07-night-2.webp", "형 노트 세 권을 들고 갔다.<br>태우려고 가져갔는데<br>태우지 못했다."],
    ["assets/situ/guy-05-night-5.webp", "3번 노트를 마지막으로 넘겼다.<br>맨 뒤 표지 안쪽에<br>종이가 한 장 더 붙어 있었다.", "shock"],
    ["assets/situ/guy-07-night-3.webp", "4번 노트였다.<br>백지였다.<br>첫 장에 한 줄만 적혀 있었다."],
    ["assets/situ/guy-07-night-4.webp", "'네가 이걸 읽고 있다면,<br>나는 또 실패한 거다.<br>이번엔 네가 써라.'", "gold", "완결"],
  ]
},
];
