const LEDE = "10년지기 동업자와 결혼을 앞둔 여자친구가 짜고 회사를 통째로 삼킨다. 옥상에서 떨어지려던 순간 시간이 거꾸로 흘러 <b>1998년, 열 살</b>로 돌아간다. 미래를 아는 채로 돈을 쓸어담고, 나를 버린 여자에게 그대로 갚아준다. 그런데 나를 부른 그 집안의 딸도 <b>회귀자</b>였고, 동맹을 거절한 대가로 고소·누명·징역이 돌아온다. 그리고 마지막에 밝혀진다 — 전생의 배신자가 <b>나보다 먼저 회귀한 최초의 회귀자</b>였다는 것을. 그림은 전부 게임에 이미 있는 에셋이며, 새로 생성한 이미지는 하나도 없습니다.";

const EPISODES = [
  {
    no: "1화",
    title: "인감은 침대 옆 서랍에 있었다",
    log: "상장을 넉 달 앞두고 10년지기 동업자에게 회사를 통째로 빼앗긴다. 위조 계약서에 찍힌 인감은 진짜였고, 그 서랍을 아는 사람은 세상에 둘뿐이었다.",
    cuts: [
      ["assets/mc-38-lux-03.png", "2026년. 서른여덟.<br>회사 지분 60%, 가을엔 상장이었다.<br>나는 다 가진 줄 알았다."],
      ["assets/situ/guy-08-date.webp", "동업자는 10년지기였다.<br>보증금 없는 반지하에서 같이 시작해,<br>2년을 무보수로 버틴 사이였다."],
      ["assets/situ/heroine-night.webp", "여자친구와는 10월에 식을 올리기로 했다.<br>예물도 신혼집도 이미 내 이름으로 끝내놨다."],
      ["assets/situ/heroine-gift.webp", "그 여자가 두 달 전<br>아이가 생긴 것 같다고 했다.<br>나는 그날 바로 식장을 잡았다.", "shock", "거짓말"],
      ["assets/mc-38-lux-02.png", "상장 실사에 들어갈 서류가 산더미였다.<br>인감은 침대 옆 서랍에 뒀다.<br>매번 금고를 여는 게 귀찮았다."],
      ["assets/situ/guy-08-gift.webp", "“형, 서류는 내가 다 처리할게.<br>형은 실사만 신경 써.”", "q"],
      ["assets/mc-male.webp", "나는 고맙다고 했다.<br>그게 마지막 실수였다."],
      ["assets/int-betrayal.webp", "6월 12일. 등기가 바뀌어 있었다.<br>내 지분 60%가 하룻밤 사이<br>통째로 넘어가 있었다.", "shock", "배신"],
      ["assets/situ/guy-01-sad.webp", "위조 계약서 한 장.<br>날짜는 석 달 전으로 소급돼 있었다.<br>그놈은 이미 그때부터 준비하고 있었다."],
      ["assets/mc-38-lux-04.png", "그런데 인감은—<br>위조가 아니었다. 진짜 내 인감이었다.", "shock", "진짜 인감"],
      ["assets/situ/heroine-night-2.webp", "그 서랍을 아는 사람은 세상에 둘.<br>나, 그리고 그 여자."],
      ["assets/situ/heroine-sad.webp", "전화를 스물세 번 걸었다.<br>스물세 번 다 받지 않았다."],
      ["assets/situ/guy-08-sad.webp", "사흘 뒤 둘이 함께 있는 걸 봤다.<br>나중에 알았다. 3년 전부터였다는 걸.", "shock", "3년"],
      ["assets/night/heroine.png", "“임신은 거짓말이었어.<br>미안. 근데 너, 이제 아무것도 없잖아.”", "q"],
      ["assets/situ/guy-02-sad.webp", "고소했다. 증거는 전부 저쪽에 있었다.<br>인감, 서류, 그리고 내 여자."],
      ["assets/situ/guy-03-sad.webp", "법원은 내가 인감을 자발적으로<br>맡긴 것으로 판단했다.<br>동거인이 꺼내 준 건 절도가 아니라고 했다."],
      ["assets/situ/guy-04-sad.webp", "석 달 뒤, 오히려 내가<br>무고죄로 역고소당했다.", "shock", "역고소"],
      ["assets/mc-30s.webp", "변호사비만 3억이 나갔다.<br>회사도, 돈도, 사람도 없었다.<br>남은 건 빚 17억이었다."],
      ["assets/int-rooftop.webp", "7월. 핸드폰이 꺼졌다.<br>충전할 돈이 없어서가 아니라<br>받을 전화가 없어서였다.<br>옥상 난간 위로 비가 내렸다."],
      ["assets/int-flash.webp", "“딱 한 번만… 다시 살 수 있다면.”<br>그 말이 새어 나온 순간<br>시간이 거꾸로 쏟아졌다.", "next", "NEXT"],
    ],
  },
  {
    no: "2화",
    title: "열 살, 용돈 3만원",
    log: "거울 속엔 열 살의 내가 있었다. 1998년 IMF의 겨울, 전 재산은 용돈 3만원. 하지만 나는 앞으로 28년을 전부 기억한다.",
    cuts: [
      ["assets/int-wake.webp", "눈을 떴다.<br>천장이 낮았다. 벽지가 촌스러웠다.<br>어디선가 라디오 소리가 났다."],
      ["assets/mc-boy.webp", "거울 앞에 섰다.<br>거울 속엔 열 살짜리가 서 있었다.", "shock", "회귀"],
      ["assets/mc-10.webp", "1998년 3월. IMF의 겨울.<br>아버지 회사가 부도난 그해였다.<br>내 전 재산은 용돈 3만원."],
      ["assets/mc-11.webp", "처음엔 미쳤다고 생각했다.<br>사흘을 앓아누웠다.<br>나흘째, 뉴스에서 아는 이름이 나왔다."],
      ["assets/int-resolve.webp", "삼성전자 900원.<br>강남 아파트 2억.<br>비트코인은 아직 세상에 없다.<br>나는 이 모든 결말을 안다.", "gold", "기억"],
      ["assets/mc-12.webp", "열 살은 계좌를 못 만든다.<br>어머니를 설득하는 데 반년이 걸렸다.<br>“엄마 이름만 빌려줘. 딱 한 번만.”"],
      ["assets/seed/sero.webp", "그해 여름, TV에서<br>무명 골퍼가 맨발로 벙커에 들어갔다.<br>온 나라가 울었다. 나는 결말을 안다."],
      ["assets/mc-13.webp", "신문 배달, 전단지, 심부름.<br>3만원이 30만원이 되는 데 1년.<br>그 돈을 전부 한 종목에 넣었다."],
      ["assets/seed/hjin.webp", "PC방에 처박혀 살던 삼촌뻘이 말했다.<br>“검색으로 세상을 다 연결할 거야.”<br>다들 미친놈이라고 했다."],
      ["assets/mc-14.webp", "나는 그 형에게 용돈을 털어 넣었다.<br>훗날 그 회사 이름은<br>모르는 사람이 없게 된다."],
      ["assets/mc-15.webp", "2000년 3월. 닷컴이 터졌다.<br>기억대로였다.<br>나는 팔았고, 남들은 샀다."],
      ["assets/mc-16.webp", "2003년. 열다섯.<br>카드대란으로 온 나라가 무너질 때<br>나는 은행주를 주웠다. 1억.", "win", "1억"],
      ["assets/seed/bong.webp", "반지하 사는 백수 형이<br>“내 영화 아무도 안 봐준다”고 중얼거렸다.<br>그 형 영화는 20년 뒤 세계를 먹는다."],
      ["assets/mc-17.webp", "2007년. 열아홉.<br>수능 대신 계좌를 봤다.<br>100억.", "win", "100억"],
      ["assets/mc-19.webp", "2008년 8월. 전부 팔았다.<br>한 달 뒤 리먼이 무너졌다.<br>선생님이 나를 이상하게 봤다."],
      ["assets/mc-20.webp", "2009년 3월. 세기의 바닥.<br>나는 전 재산을 던져 넣었다.<br>스무 살 생일이었다.", "gold", "전력 매수"],
      ["assets/seed/hson.webp", "공터에서 볼 리프팅 만 개를 채우던 꼬마.<br>아버지가 미쳤다고들 했다.<br>나는 그 아이 이름을 기억한다."],
      ["assets/mc-22.webp", "2010년. 스물둘.<br>1000억을 넘겼다.<br>아무도 내가 누군지 몰랐다.", "win", "1000억"],
      ["assets/mc-25.webp", "2013년. 스물다섯.<br>이 나라에서 제일 어린 부자가 됐다.<br>돈으로 못 사는 게 없어졌다."],
      ["assets/situ/heroine-date.webp", "그리고 나는—<br>그 여자를 찾기 시작했다.", "next", "NEXT"],
    ],
  },
  {
    no: "3화",
    title: "결혼식 날, 신부는 혼자 서 있었다",
    log: "전생에 나를 버린 여자를 찾아낸다. 문제는 2013년의 그 사람이 아직 아무 죄도 짓지 않았다는 것이었다.",
    cuts: [
      ["assets/situ/heroine-sad.webp", "2013년. 그 여자를 찾아냈다.<br>스물여덟, 중소기업 경리.<br>전생에 나를 버린 그 얼굴 그대로였다.", "shock", "재회"],
      ["assets/mc-26.webp", "전생의 배신은 아직 일어나지 않았다.<br>그 여자는 아직 아무 죄가 없다.<br>알면서도 나는 다가갔다."],
      ["assets/mc-27.webp", "전생에 그 여자가 좋아했던 것을<br>나는 전부 알고 있었다.<br>취향, 노래, 상처까지."],
      ["assets/situ/heroine-gift.webp", "두 달 만에 그 여자는 무너졌다.<br>“오빠는 내 마음을 어떻게 그렇게 잘 알아?”"],
      ["assets/situ/girl-06-gift.webp", "차를 사줬다. 집을 사줬다.<br>어머니 병원비까지 내가 냈다.<br>그 여자 가족이 나를 아들이라 불렀다."],
      ["assets/situ/heroine-travel.webp", "1년이 지났다.<br>그 여자는 나 없인 못 산다고 했다.<br>이제 됐다고 생각했다."],
      ["assets/situ/girl-07-gift.webp", "청혼했다.<br>그 여자는 울면서 손을 떨었다."],
      ["assets/situ/heroine-wed.webp", "식장을 잡았다.<br>전생에 우리가 잡았던, 바로 그 식장으로.", "shock", "바로 그 식장"],
      ["assets/situ/girl-08-wed.webp", "하객 300명.<br>양가 친척이 전부 왔다.<br>그 여자는 새벽 5시부터 준비했다."],
      ["assets/mc-30.webp", "2015년 5월 9일. 결혼식 당일."],
      ["assets/mc-38-lux-09.png", "나는 식장에 가지 않았다.<br>그 시간에 나는 발리에 있었다.<br>신부 대기실로 사진 한 장을 보냈다.", "shock", "복수"],
      ["assets/situ/heroine-night-3.webp", "“오빠 어디야. 왜 안 와.<br>사람들이 다 보고 있어. 제발.”", "q"],
      ["assets/mc-38-lux-10.png", "“전생에 네가 나한테 했던 거야.”"],
      ["assets/situ/girl-09-sad.webp", "그 여자는 그 말을 이해하지 못했다.<br>당연했다. 아직 아무것도 안 했으니까."],
      ["assets/situ/heroine-night-4.webp", "그 여자는 웨딩드레스를 입은 채<br>식장에 세 시간을 서 있었다.<br>하객들이 하나씩 빠져나갔다."],
      ["assets/situ/girl-10-sad.webp", "그날 밤 전화가 마흔한 통 왔다.<br>나는 한 통도 받지 않았다."],
      ["assets/situ/heroine-night-5.webp", "마지막 문자는 이랬다.<br>“너, 이거 반드시 후회하게 해줄게.”", "shock", "씨앗"],
      ["assets/mc-31.webp", "흔한 말인 줄 알았다.<br>이 한마디가 4년 뒤<br>나를 감옥에 넣는다."],
      ["assets/situ/guy-08-travel.webp", "참, 그 배신자는—<br>이번 생엔 그냥 평범한 회사원이다.<br>내가 갈 길을 전부 막아놨으니까.", "gold", "후일담"],
      ["assets/night/girl-heiress.png", "그 무렵, 한 그룹에서 연락이 왔다.<br>전생에 내 회사를 최종적으로 삼킨<br>바로 그 집안이었다.", "next", "NEXT"],
    ],
  },
  {
    no: "4화",
    title: "거절하지 말았어야 했다",
    log: "협상 자리에 나온 그 집 딸은 서류를 보지 않았다. 대신 내 매매 기록을 짚었다. 2000년 3월, 2008년 8월, 2009년 3월.",
    cuts: [
      ["assets/situ/girl-heiress-date.webp", "협상 자리에 그 집 딸이 직접 나왔다.<br>스물여섯. 후계자 수업 중이라고 했다."],
      ["assets/mc-32.webp", "그 여자는 서류를 펴지도 않았다.<br>대신 내 매매 기록을 꺼냈다."],
      ["assets/situ/girl-heiress-gift.webp", "“오빠, 2000년 3월에<br>왜 전부 팔았어요?”", "q"],
      ["assets/mc-33.webp", "공시에 남는 기록이다.<br>운이 좋았다고 하면 그만이다."],
      ["assets/situ/girl-heiress-travel.webp", "“2008년 8월엔 왜 또 다 팔았죠?<br>2009년 3월엔 왜 전부 샀고요?”", "q"],
      ["assets/mc-34.webp", "세 번은 우연이 아니다.<br>등에서 식은땀이 났다.", "shock", "발각"],
      ["assets/situ/girl-heiress-night.webp", "“나도 그랬거든요.”"],
      ["assets/mc-35.webp", "그 여자의 거래 기록을 받아봤다.<br>날짜가 나와 똑같았다.<br>단 한 번, 2013년만 달랐다."],
      ["assets/situ/girl-heiress-night-2.webp", "“거긴 내가 못 샀어요.<br>오빠가 먼저 사버려서.”", "q"],
      ["assets/situ/girl-heiress-night-3.webp", "이 여자도— 회귀자다.", "shock", "반전"],
      ["assets/situ/guy-08-wed.webp", "“전생에 나, 그 사람이랑 결혼했었어요.”<br>그 여자가 말한 이름은<br>내 동업자였다.", "shock", "연결"],
      ["assets/situ/guy-heir-date.webp", "“우리 아버지가 오빠 회사를 삼키고,<br>나를 그 사람한테 붙였어요.<br>합병 조건이었죠.”"],
      ["assets/situ/guy-heir-gift.webp", "“결혼식 다음 날부터 맞았어요.<br>3년을 참다가 옥상에서 뛰어내렸고,<br>눈 떠보니 열여덟이었어요.”", "shock", "지옥"],
      ["assets/situ/girl-heiress-wed.webp", "“그러니까 우리, 같은 배에 탄 거야.”"],
      ["assets/situ/guy-heir-sad.webp", "“손잡자. 둘이 아는 걸 합치면<br>이 나라 시장은 우리 거야.”", "q"],
      ["assets/mc-36.webp", "미래를 아는 사람이 둘이면<br>미래는 더 이상 무기가 아니다.<br>먼저 쓰는 쪽이 다 가져간다."],
      ["assets/mc-37.webp", "손을 잡는 순간<br>내 기억은 전부 저쪽으로 넘어간다.<br>그리고 나는 필요 없어진다."],
      ["assets/mc-38.webp", "나는 거절했다.", "shock", "거절"],
      ["assets/situ/girl-heiress-sad.webp", "그 여자는 웃으면서 일어섰다.<br>“…그래요. 그럼 어쩔 수 없죠.”", "shock", "경고"],
      ["assets/situ/guy-09-sad.webp", "다음 주부터<br>이상한 일이 시작됐다.", "next", "NEXT"],
    ],
  },
  {
    no: "5화",
    title: "시장은 알아도 악의는 모른다",
    log: "회귀자끼리의 싸움은 서로의 기억을 갉아먹는다. 1년 만에 그 여자가 방식을 바꾼다. 시장이 아니라 사람을 쓰기 시작한 것이다.",
    cuts: [
      ["assets/situ/guy-10-sad.webp", "내가 사려던 종목마다<br>누가 먼저 들어와 있었다.<br>단 하루씩 빨랐다."],
      ["assets/mc-38-lux-05.png", "가격이 내가 아는 값이 아니었다.<br>당연했다. 그 여자도 같은 기억을 갖고 있으니까."],
      ["assets/situ/guy-11-sad.webp", "나는 종목을 바꿨다.<br>그 여자가 따라왔다.<br>내가 아는 걸 그 여자도 아니까."],
      ["assets/mc-38-lux-06.png", "나는 그 여자가 살 것을<br>미리 사서 비싸게 되팔았다.<br>서로의 기억을 갉아먹는 싸움이었다."],
      ["assets/situ/guy-12-sad.webp", "내 회사 지분이 조용히 팔려나갔다.<br>차명 계좌 수십 개였다.<br>추적하면 전부 다른 이름이 나왔다."],
      ["assets/mc-38-lux-07.png", "1년이 지났다.<br>둘 다 손해였다.<br>그리고 그 여자가 방식을 바꿨다."],
      ["assets/situ/guy-13-sad.webp", "시장이 아니라—<br>사람을 쓰기 시작했다.", "shock", "전환"],
      ["assets/situ/girl-13-sad.webp", "어느 날 내 회사 로비에<br>낯익은 얼굴이 앉아 있었다."],
      ["assets/situ/girl-06-sad.webp", "사진 속 얼굴을 보고<br>나는 숨이 막혔다."],
      ["assets/situ/heroine-wed.webp", "3화에서 나 때문에<br>웨딩드레스를 입고 세 시간을 서 있던<br>바로 그 여자였다.", "shock", "결탁"],
      ["assets/situ/girl-09-gift.webp", "두 사람이 마주 앉아 있었다.<br>한쪽은 돈과 로펌.<br>한쪽은 4년치 원한."],
      ["assets/situ/girl-10-gift.webp", "“그 사람이 나한테<br>뭘 했는지 아세요?”", "q"],
      ["assets/situ/girl-11-gift.webp", "“결혼식 날, 신부 혼자<br>식장에 세 시간을 서 있었어요.<br>사람들이 전부 보는 앞에서요.”", "q"],
      ["assets/mc-38-lux-08.png", "나한테 없는 게 저쪽엔 있었다."],
      ["assets/mc-38-lux-09.png", "나는 시장은 안다.<br>어느 종목이 오르는지, 언제 무너지는지."],
      ["assets/mc-38-lux-10.png", "하지만 사람의 악의는 모른다.<br>그건 내 기억에 없던 일이니까.", "gold", "약점"],
      ["assets/situ/guy-14-sad.webp", "전생의 나는 이 시기에<br>아무 일도 겪지 않았다.<br>평범하게 회사를 키우고 있었다."],
      ["assets/situ/guy-15-sad.webp", "내가 복수를 했기 때문에<br>생겨난 미래였다.", "shock", "자업자득"],
      ["assets/mc-38-lux-01.png", "내가 만든 적이었다.<br>그리고 나는 이 적을 모른다."],
      ["assets/situ/guy-01-sad.webp", "2019년 3월.<br>고소장이 접수됐다.", "next", "NEXT"],
    ],
  },
  {
    no: "6화",
    title: "전생과 똑같은 수법",
    log: "혼인빙자는 2009년에 폐지됐다. 죄목은 사기였다. 내가 사인한 적 없는 계약서에 또 내 인감이 찍혀 있었다.",
    cuts: [
      ["assets/situ/guy-02-sad.webp", "혼인빙자? 그건 2009년에 폐지됐다.<br>죄목은 사기였다."],
      ["assets/situ/guy-03-sad.webp", "결혼을 전제로 오간 재산.<br>차, 집, 예물, 병원비.<br>전부 내 돈으로 산 것들이었다."],
      ["assets/situ/girl-17-sad.webp", "그 여자는 그걸<br>‘맡긴 돈’이라고 주장했다."],
      ["assets/situ/girl-18-sad.webp", "“결혼을 조건으로<br>제 명의 자금을 맡겼습니다.<br>그 사람은 그걸 굴려서 불렸고요.”", "q"],
      ["assets/mc-26.webp", "말도 안 되는 소리였다.<br>그런데 계약서가 있었다."],
      ["assets/situ/girl-19-sad.webp", "내가 사인한 적 없는 계약서.<br>2013년 날짜로 소급돼 있었다."],
      ["assets/mc-27.webp", "그런데 인감은— 진짜였다.", "shock", "데자뷔"],
      ["assets/situ/heroine-night-6.webp", "전생과 똑같은 수법이었다.<br>그때도 침대 옆 서랍,<br>이번엔 사무실 금고.", "shock", "같은 수법"],
      ["assets/mc-28.webp", "1년을 같이 산 사람은<br>내 금고 비밀번호를 안다.<br>나는 또 같은 실수를 했다."],
      ["assets/situ/guy-heir-wed.webp", "그 집안 로펌이 붙었다.<br>변호사만 열한 명."],
      ["assets/mc-29.webp", "나는 열다섯 명을 붙였다.<br>돈으로는 지지 않았다."],
      ["assets/situ/guy-heir-travel.webp", "그런데 회사에서<br>감사팀이 나를 불렀다."],
      ["assets/situ/guy-04-night.webp", "없던 횡령 기록이<br>내 이름으로 만들어져 있었다.<br>3년치, 47억.", "shock", "누명"],
      ["assets/mc-30.webp", "내부자가 있다는 뜻이었다."],
      ["assets/situ/guy-05-night.webp", "재무이사가 그 집안 사람이었다.<br>2년 전에 내가 직접 뽑은 사람.", "shock", "심어둔 말"],
      ["assets/mc-31.webp", "그 여자는 2년 전부터<br>이 판을 깔고 있었다.<br>내가 거절한 그날부터."],
      ["assets/situ/guy-06-night.webp", "계좌가 동결됐다.<br>변호사비를 낼 현금이 없어졌다.<br>미래를 아는 것과 지금 현금은 다른 문제다."],
      ["assets/situ/guy-07-night.webp", "1심 유죄.<br>2심에서 형이 확정됐다."],
      ["assets/mc-32.webp", "징역 2년.", "shock", "실형"],
      ["assets/situ/guy-08-night.webp", "회귀자의 무기는 미래를 아는 것.<br>감옥에선 아무 쓸모가 없다.", "next", "NEXT"],
    ],
  },
  {
    no: "7화",
    title: "회귀자는 언제 전부를 거는가",
    log: "2년이면 기억의 유효기간도 2년 줄어든다. 감옥에서 계산한 건 그 여자가 뭘 살지가 아니라, 언제 전 재산을 걸지였다.",
    cuts: [
      ["assets/situ/guy-09-night.webp", "2017년 겨울. 수감.<br>독방은 세 평이었다."],
      ["assets/mc-33.webp", "미래를 아는 사람에게<br>2년은 특별히 길다."],
      ["assets/situ/guy-10-night.webp", "내 기억의 유효기간이<br>2년만큼 줄어든 것이다.<br>2019년에 나오면 남은 건 7년치.", "gold", "기억의 소모"],
      ["assets/mc-34.webp", "그리고 그 여자도<br>똑같이 2년을 앞서간다.<br>가만히 있어도 나만 손해다."],
      ["assets/situ/guy-11-night.webp", "매일 같은 계산을 반복했다.<br>그 여자가 뭘 살지가 아니라—"],
      ["assets/mc-35.webp", "언제 전부를 걸지를 계산했다.", "gold", "급소"],
      ["assets/situ/guy-12-night.webp", "회귀자는 어지간해선 전부를 안 건다.<br>기억이 남아 있는 한 다음 기회가 있으니까."],
      ["assets/mc-36.webp", "하지만 딱 한 번,<br>확신하는 순간이 온다.<br>내 기억에 그런 순간은 하나뿐이었다."],
      ["assets/situ/guy-13-night.webp", "2020년 3월.<br>모두가 파는 그날."],
      ["assets/situ/girl-05-night.webp", "수감 8개월째, 면회가 왔다."],
      ["assets/situ/girl-heiress-night-4.webp", "그 여자였다.<br>변호사도 없이 혼자 왔다."],
      ["assets/mc-37.webp", "“오빠, 이제 알겠지?<br>미래를 안다고 이길 수 있는 게 아니야.”", "q"],
      ["assets/situ/girl-06-night.webp", "“나 못 이겨. 그냥 인정해.”", "q"],
      ["assets/mc-38.webp", "나는 아무 말도 하지 않았다.<br>그게 그 여자를 안심시켰다."],
      ["assets/situ/girl-07-night.webp", "그 여자는 내가 밖에<br>아무것도 못 남겼다고 믿었다.<br>계좌를 전부 털었으니까."],
      ["assets/situ/guy-01-wed.webp", "틀렸다.<br>1998년에 어머니 이름으로 만든<br>그 첫 계좌가 남아 있었다.", "gold", "복선 회수"],
      ["assets/mc-38-lux-02.png", "스물한 해 전 계좌다.<br>아무도 나와 연결짓지 못한다."],
      ["assets/situ/guy-02-wed.webp", "면회 오는 사촌에게<br>매달 종목 하나씩만 말했다.<br>2년 동안 스물넷."],
      ["assets/situ/guy-03-wed.webp", "2019년 겨울. 출소.<br>주머니에 5만원이 있었다."],
      ["assets/situ/guy-04-wed.webp", "계좌를 열어봤다.<br>거기엔 생각보다 많은 게 들어 있었다.", "next", "NEXT"],
    ],
  },
  {
    no: "8화",
    title: "레버리지는 바닥을 못 기다린다",
    log: "그 여자는 반등을 확신하고 레버리지를 최대로 당겼다. 판단은 맞았다. 문제는 반대매매가 바닥보다 이틀 먼저 온다는 것이었다.",
    cuts: [
      ["assets/situ/guy-05-wed.webp", "출소하고 석 달간<br>나는 아무것도 하지 않았다."],
      ["assets/mc-38-lux-03.png", "정확히는,<br>눈에 띄는 걸 하지 않았다."],
      ["assets/situ/guy-06-wed.webp", "그 여자는 내가<br>재기 못 한다고 판단했다.<br>그게 내가 원한 것이었다."],
      ["assets/situ/guy-07-wed.webp", "차명 계좌 스물넷에<br>현금만 쌓았다.<br>주식은 한 주도 사지 않았다."],
      ["assets/mc-38-lux-04.png", "2020년 1월.<br>뉴스에 낯익은 단어가 나왔다."],
      ["assets/situ/guy-08-night-2.webp", "코로나.<br>기억대로였다."],
      ["assets/situ/girl-heiress-travel.webp", "그 여자도 봤을 것이다.<br>같은 기억을 갖고 있으니까."],
      ["assets/mc-38-lux-05.png", "회귀자는 확신하면 전부 건다.<br>그 여자에게 이건<br>인생을 되찾을 단 한 번의 기회다."],
      ["assets/situ/girl-heiress-date.webp", "2월. 그 여자가 움직였다.<br>보유 자산 전량을 담보로<br>레버리지를 최대로 당겼다."],
      ["assets/mc-38-lux-06.png", "폭락 직전에, 반등을 확신하고."],
      ["assets/situ/guy-09-wed.webp", "맞는 판단이었다.<br>3월 19일이 바닥이니까."],
      ["assets/mc-38-lux-07.png", "문제는 3월 19일까지<br>버틸 수 있느냐였다.", "gold", "급소"],
      ["assets/situ/guy-10-wed.webp", "레버리지는 바닥을 못 기다린다.<br>담보 비율이 무너지면<br>증권사가 알아서 판다."],
      ["assets/mc-38-lux-08.png", "반대매매는 바닥보다 먼저 온다.<br>항상.", "gold", "규칙"],
      ["assets/situ/guy-11-wed.webp", "3월 12일. 첫 마진콜.<br>3월 16일. 두 번째."],
      ["assets/situ/guy-12-wed.webp", "3월 17일 오전 9시 3분.<br>그 여자 물량이 강제청산됐다.", "shock", "청산"],
      ["assets/mc-38-lux-09.png", "나는 현금이었다.<br>쏟아지는 물량을 전부 받았다.", "gold", "인수"],
      ["assets/situ/guy-13-wed.webp", "3월 19일. 바닥이 왔다.<br>그리고 기억대로 올랐다."],
      ["assets/car-rolls.png", "2021년.<br>그 여자는 담보로 잡힌 지분까지<br>전부 잃었다.", "win", "역전"],
      ["assets/situ/girl-heiress-sad.webp", "“…어떻게 알았어?”<br>“네가 나한테 알려줬잖아.”", "next", "NEXT"],
    ],
  },
  {
    no: "9화",
    title: "넉 달 전에 이미 알고 있었다",
    log: "전 여자친구가 찾아와 증언한다. 배신 넉 달 전, 그가 먼저 접근해 “이 남자 곧 망한다”고 했다는 것이다. 상장 직전의 회사가 망할 이유는 없었다.",
    cuts: [
      ["assets/situ/heroine-night.webp", "2021년 가을.<br>전 여자친구가 나를 찾아왔다."],
      ["assets/situ/heroine-sad.webp", "소송에서 지고,<br>그 집안에서도 버려진 뒤였다.<br>이용 가치가 없어졌으니까."],
      ["assets/mc-38-lux-10.png", "무슨 낯으로 왔냐고 물었다."],
      ["assets/situ/heroine-travel.webp", "“나… 할 말이 있어.<br>이건 말해야 할 것 같아서.”", "q"],
      ["assets/situ/heroine-gift.webp", "“2026년에, 그 사람이<br>먼저 나한테 접근했었어.”", "shock", "증언"],
      ["assets/mc-26.webp", "2026년? 그건 전생 얘기다.<br>이 여자는 회귀자가 아니다.<br>그런데 왜 전생을 기억하지?"],
      ["assets/situ/heroine-night-2.webp", "“무슨 소리야. 2026년이면 아직 멀었잖아.<br>내가 말한 건 그 사람이 나한테<br>처음 연락한 날 얘기야. 2013년 3월.”", "q"],
      ["assets/mc-27.webp", "2013년 3월.<br>내가 그 여자에게 접근하기<br>두 달 전이었다.", "shock", "두 달 전"],
      ["assets/situ/heroine-wed.webp", "“그 사람이 그랬어.<br>곧 어떤 남자가 너한테 올 거다.<br>그 남자, 곧 망한다고.”", "q"],
      ["assets/mc-28.webp", "상장 직전의 회사가<br>망할 이유는 없었다.<br>망하게 될 걸 안 게 아니라—"],
      ["assets/mc-29.webp", "망하게 만들 걸<br>알고 있었던 거다.", "shock", "설계"],
      ["assets/situ/guy-01-date.webp", "나는 그놈의 계좌를 뒤졌다.<br>이번 생엔 평범한 회사원인 그놈을."],
      ["assets/situ/guy-02-date.webp", "차명 계좌 47개가 나왔다.<br>평범한 회사원의 계좌가 아니었다."],
      ["assets/mc-30.webp", "가장 오래된 계좌는<br>1998년 개설.", "shock", "1998"],
      ["assets/situ/guy-03-date.webp", "그놈은 나와 동갑이다.<br>1998년이면 열 살이었다."],
      ["assets/mc-31.webp", "열 살이 만들 수 있는 계좌가 아니다.<br>나는 어머니 이름을 빌렸다.<br>그놈은 할머니 이름을 빌렸다."],
      ["assets/situ/guy-04-date.webp", "매수 종목이 나와 겹쳤다.<br>삼성전자, 네이버, 그리고 그 골퍼."],
      ["assets/mc-32.webp", "다만 항상—<br>나보다 며칠씩 빨랐다.", "shock", "반전"],
      ["assets/situ/guy-05-date.webp", "그놈도 회귀자였다.<br>그것도 나보다 먼저.<br>10년을 친구인 척하며 기다린 것이다."],
      ["assets/int-rooftop.webp", "그놈이 먼저 연락해왔다.<br>“네가 처음 죽은 그 자리에서 보자.”", "next", "NEXT"],
    ],
  },
  {
    no: "10화",
    title: "세 번 살았다",
    log: "옥상에 선 그는 세 번을 살았다고 했다. 첫 번째는 아무것도 몰라서, 두 번째는 나에게 밀려서. 그래서 세 번째엔 나부터 없애기로 했다.",
    cuts: [
      ["assets/situ/guy-06-date.webp", "2026년 7월. 그 옥상.<br>비가 오지 않는 것만 달랐다."],
      ["assets/situ/guy-08-night-3.webp", "그놈이 난간에 서 있었다.<br>10년지기의 얼굴로."],
      ["assets/mc-33.webp", "“왜 나였나.”", "q"],
      ["assets/situ/guy-07-date.webp", "“네가 제일 운이 좋았거든.”", "q"],
      ["assets/situ/guy-09-date.webp", "“나는 세 번 살았어.”", "shock", "세 번"],
      ["assets/mc-34.webp", "세 번."],
      ["assets/situ/guy-10-date.webp", "“첫 번째는 아무것도 몰라서 망했고,”"],
      ["assets/situ/guy-11-date.webp", "“두 번째는— 너한테 밀렸지.<br>내가 사려던 걸 네가 먼저 샀거든.”"],
      ["assets/mc-35.webp", "“그래서 세 번째엔<br>너부터 없애기로 했다.”", "q"],
      ["assets/situ/guy-08-gift.webp", "그래서 10년을 친구로 살았다.<br>반지하에서 같이 라면을 먹으면서."],
      ["assets/mc-36.webp", "그래서 전생에 나를<br>옥상까지 몰았던 거다.<br>죽으라고."],
      ["assets/situ/guy-08-travel.webp", "“그런데 네가 회귀할 줄은 몰랐어.”", "shock", "오산"],
      ["assets/mc-37.webp", "회귀는 죽기 직전에만 열린다."],
      ["assets/situ/guy-08-sad.webp", "나를 죽인 게 아니라<br>죽고 싶게 만든 게 그놈의 실수였다.", "gold", "자충수"],
      ["assets/situ/girl-heiress-night.webp", "그때 옥상 문이 열렸다.<br>부잣집 딸이 올라왔다."],
      ["assets/situ/heroine-night-3.webp", "그 뒤로 전 여자친구도 올라왔다.<br>둘 다 그놈한테 이용당한 쪽이었다."],
      ["assets/situ/girl-16-sad.webp", "우리 셋은 같은 사람한테<br>인생을 뺏겼다.<br>방식만 달랐을 뿐이다."],
      ["assets/mc-38-lux-01.png", "그놈이 웃었다. “그래서 뭐.”"],
      ["assets/situ/guy-12-date.webp", "나는 계좌 47개 자료를<br>검찰에 넘겼다.<br>미래를 아는 건 죄가 아니지만—", "win", "증거"],
      ["assets/situ/guy-13-date.webp", "차명 47개는 죄다.<br>경찰이 옥상으로 올라왔다.", "next", "NEXT"],
    ],
  },
  {
    no: "11화",
    title: "47개의 계좌는 누구 것도 아니었다",
    log: "명의자 47명 중 절반은 사망, 나머지는 해외 거주였다. 28년에 걸쳐 짜맞춘 구조 앞에서 증거는 증거가 되지 못했다.",
    cuts: [
      ["assets/situ/guy-14-night.webp", "재판이 시작됐다.<br>검찰은 차명 계좌 47개를 제출했다."],
      ["assets/situ/guy-15-night.webp", "명의자는 47명.<br>변호인이 명단을 읽어 내려갔다."],
      ["assets/mc-38-lux-02.png", "절반은 이미 사망했다.<br>가장 오래된 명의자는<br>2004년에 죽은 그놈 할머니였다."],
      ["assets/situ/girl-08-night.webp", "나머지는 전부 해외 거주.<br>소환장이 닿지 않는 곳들이었다."],
      ["assets/mc-38-lux-03.png", "그놈 이름은 어디에도 없었다.<br>단 한 장의 서류에도.", "shock", "공백"],
      ["assets/situ/girl-09-night.webp", "“제 계좌가 아닙니다.<br>할머니 유산 관리를 도왔을 뿐입니다.”", "q"],
      ["assets/mc-38-lux-04.png", "자금 흐름은 있는데<br>소유자가 없다."],
      ["assets/situ/girl-10-night.webp", "1998년부터 28년에 걸쳐<br>한 겹씩 쌓아 올린 구조였다.<br>서두른 흔적이 하나도 없었다."],
      ["assets/mc-38-lux-05.png", "회귀자는 돈보다<br>법을 먼저 배운다.<br>어디까지가 안 걸리는지를 아니까.", "gold", "설계"],
      ["assets/situ/girl-11-night.webp", "증거 불충분."],
      ["assets/situ/guy-01-night.webp", "무죄.", "shock", "무죄"],
      ["assets/mc-38-lux-06.png", "법정을 나오며 그놈이<br>내 어깨를 툭 쳤다."],
      ["assets/situ/guy-08-night-4.webp", "“네 기억, 언제까지<br>남아 있을 것 같냐?”", "shock", "급소"],
      ["assets/mc-38-lux-07.png", "나는 대답을 못 했다."],
      ["assets/situ/girl-12-night.webp", "2026년 7월 15일.<br>내가 회귀한 그날.<br>거기까지가 내 기억이다.", "gold", "기억의 끝"],
      ["assets/mc-38-lux-08.png", "앞으로 남은 건 11개월.<br>그 뒤로는 나도 아무것도 모른다."],
      ["assets/situ/girl-13-night.webp", "그놈은 세 번 살았다.<br>나보다 한 번 더 안다."],
      ["assets/mc-38-lux-09.png", "그 한 번의 차이가<br>얼마나 큰지 나는 몰랐다."],
      ["assets/situ/girl-14-night.webp", "그놈에겐 아직<br>카드가 남아 있었다."],
      ["assets/situ/guy-02-date.webp", "8월. 지분 공시가 떴다.", "next", "NEXT"],
    ],
  },
  {
    no: "12화",
    title: "2%가 모자랐다",
    log: "누군가 내 회사 지분 5%를 사들여 공시가 떴다. 조합원 명단에 그놈 할머니의 성씨가 있었다. 이번 표적은 시장이 아니라 회사였다.",
    cuts: [
      ["assets/situ/guy-03-date.webp", "누군가 내 회사 5%를 사들였다.<br>5%를 넘기면 공시 의무가 생긴다."],
      ["assets/situ/guy-04-date.webp", "명의는 신설 투자조합.<br>설립일은 두 달 전이었다."],
      ["assets/mc-38-lux-10.png", "조합원 명단을 훑다가 멈췄다.<br>익숙한 성씨가 있었다."],
      ["assets/situ/guy-05-date.webp", "그놈 할머니의 성씨.<br>또 차명이었다.", "shock", "또 차명"],
      ["assets/mc-26.webp", "이번 표적은 시장이 아니라<br>내 회사였다."],
      ["assets/situ/guy-09-date.webp", "미래를 알아도<br>내 지분은 51%가 안 됐다.<br>상장하면서 희석됐으니까.", "gold", "약점"],
      ["assets/mc-27.webp", "정확히 38%.<br>나머지는 소액주주와 기관이었다."],
      ["assets/situ/guy-10-date.webp", "그놈이 주가를 띄우기 시작했다.<br>한 달 만에 40% 올랐다."],
      ["assets/mc-28.webp", "주주들은 돈을 따라간다.<br>내가 아무리 옳아도<br>당장 주가를 올리는 쪽을 찍는다."],
      ["assets/situ/guy-11-date.webp", "임시주총 소집 요구서가 왔다.<br>안건은 대표이사 해임.", "shock", "표 대결"],
      ["assets/situ/guy-12-date.webp", "표를 세어봤다.<br>몇 번을 세어도 답이 같았다."],
      ["assets/mc-29.webp", "2%가 모자랐다.", "shock", "2%"],
      ["assets/situ/guy-13-date.webp", "우호지분을 전부 훑었다.<br>더 나올 데가 없었다."],
      ["assets/situ/girl-15-night.webp", "그때 모르는 번호로<br>전화가 왔다."],
      ["assets/situ/girl-heiress-travel.webp", "부잣집 딸이었다.<br>1년 만이었다."],
      ["assets/mc-30.webp", "그 여자는 2020년에<br>전부 잃었다. 나 때문에.<br>그런데 지분은 남아 있었다."],
      ["assets/situ/girl-heiress-gift.webp", "“내 지분, 오빠한테 줄게.<br>3.2%. 딱 이기고도 남아.”", "q"],
      ["assets/mc-31.webp", "왜 도와주냐고 물었다."],
      ["assets/situ/girl-heiress-night-2.webp", "“나 그 사람이랑 두 번 결혼했어.<br>전생에 한 번, 그리고—<br>지난달에 또.”", "shock", "또 그놈"],
      ["assets/situ/girl-16-night.webp", "“대신, 조건이 있어.”", "next", "NEXT"],
    ],
  },
  {
    no: "13화",
    title: "조건",
    log: "조건은 돈이 아니었다. 아이를 찾아달라는 것이었다. 세 번을 살고도 자식이 없던 남자가 후계자를 만들려 하고 있었다.",
    cuts: [
      ["assets/situ/girl-heiress-night-3.webp", "“그 사람 아이를 찾아줘.”", "q"],
      ["assets/mc-32.webp", "무슨 아이냐고 물었다."],
      ["assets/situ/girl-heiress-wed.webp", "“전 여자친구가 낳은 아이.<br>2016년생. 그 사람 아이야.”", "shock", "아이"],
      ["assets/situ/heroine-night-4.webp", "내가 식장에 안 간 그해,<br>그 여자는 그놈에게 갔다.<br>나는 그것도 모르고 있었다."],
      ["assets/mc-33.webp", "그놈은 나를 무너뜨리려고<br>그 여자를 이용했고,<br>그 여자는 그놈의 아이를 낳았다."],
      ["assets/situ/heroine-night-5.webp", "아이는 두 살에 보육원에 맡겨졌다.<br>둘 다 아이를 원하지 않았다."],
      ["assets/mc-34.webp", "왜 지금 와서 찾느냐고 물었다."],
      ["assets/situ/girl-heiress-night-4.webp", "“그 사람이 그 아이를<br>후계자로 만들려고 해.<br>지난주에 친자 인지 신청을 냈어.”", "shock", "목적"],
      ["assets/mc-35.webp", "회귀자는 자기 핏줄에 집착한다.<br>세 번을 살았지만<br>자식은 한 번도 없었으니까.", "gold", "동기"],
      ["assets/situ/girl-17-sad.webp", "그 아이 앞으로 계좌를 만들고,<br>차명 47개를 전부 물려주면—"],
      ["assets/mc-36.webp", "네 번째 판이 시작된다.<br>이번엔 그놈이 아니라<br>그놈의 아이가 두는 판이.", "shock", "다음 판"],
      ["assets/situ/guy-14-date.webp", "나는 보육원을 찾아냈다.<br>경기도 외곽이었다."],
      ["assets/mc-16.webp", "아이는 열 살이 되어 있었다.<br>내가 회귀했던 그 나이였다."],
      ["assets/mc-17.webp", "아이는 아무것도 몰랐다.<br>아버지가 누군지도,<br>자기가 무엇에 쓰일지도."],
      ["assets/situ/guy-15-date.webp", "나는 원장에게 물었다.<br>“이 아이 앞으로 들어온 돈이 있습니까.”"],
      ["assets/mc-18.webp", "있었다.<br>2016년부터 매달, 익명으로.<br>보낸 사람은 나였다.", "gold", "복선 회수"],
      ["assets/mc-20.webp", "그때 나는 그 아이가<br>내 아이인 줄 알았다.<br>친자가 아닌 걸 알고도 끊지 않았다."],
      ["assets/mc-21.webp", "10년간 쌓인 돈이<br>스무 배가 되어 있었다.<br>내가 종목을 골라줬으니까."],
      ["assets/mc-23.webp", "아이는 이미 스스로 살 수 있었다.<br>그놈이 줄 수 있는 게 없어진 것이다.", "win", "3차 방어"],
      ["assets/situ/girl-heiress-sad.webp", "부잣집 딸이 지분을 넘겼다.<br>주총에서 나는 2%를 이겼다.", "next", "NEXT"],
    ],
  },
  {
    no: "14화",
    title: "기억의 마지막 페이지",
    log: "2026년 7월 15일. 내가 회귀한 그날이 왔다. 28년 만에 처음으로, 내일을 모른다.",
    cuts: [
      ["assets/mc-38-lux-01.png", "2026년 7월 15일."],
      ["assets/int-rooftop.webp", "내가 회귀한 그날이었다.<br>28년 전 그 옥상에서<br>모든 게 시작됐다."],
      ["assets/mc-38-lux-02.png", "여기까지가 내 기억이다.", "gold", "마지막 페이지"],
      ["assets/mc-38-lux-03.png", "내일부터는—<br>아무것도 모른다.", "shock", "공백"],
      ["assets/situ/girl-18-sad.webp", "28년 만에 처음이었다.<br>아침에 뉴스를 봤는데<br>다음 문장이 떠오르지 않았다."],
      ["assets/mc-22.webp", "손이 떨렸다.<br>주문 버튼을 누르지 못했다."],
      ["assets/situ/girl-19-sad.webp", "평생 미래를 아는 게<br>내 실력이라고 믿었다."],
      ["assets/mc-24.webp", "그게 없어지니<br>나는 아무것도 아니었다.", "shock", "민낯"],
      ["assets/situ/guy-01-gift.webp", "그놈은 한 번 더 안다.<br>2026년 7월 이후를<br>그놈만 알고 있다."],
      ["assets/mc-teen.webp", "그날부터 그놈이 사기 시작했다.<br>내가 이름도 모르는 종목들이었다."],
      ["assets/situ/guy-02-gift.webp", "따라 살 수도 있었다.<br>하지만 그건 그놈이<br>가장 원하는 그림이었다."],
      ["assets/mc-young.webp", "따라 사는 순간<br>나는 그놈 손바닥 위에 올라간다."],
      ["assets/situ/guy-03-gift.webp", "나는 따라 사지 않았다.<br>대신 그놈 계좌를 감시했다."],
      ["assets/mc-rich.webp", "그놈이 뭘 사는지가<br>곧 미래니까.", "gold", "지표"],
      ["assets/situ/guy-04-gift.webp", "회귀자를 이기는 마지막 방법은<br>그놈을 지표로 쓰는 것이었다."],
      ["assets/situ/guy-05-gift.webp", "9월. 그놈이 반도체를 담았다.<br>나는 기록만 했다."],
      ["assets/situ/guy-06-gift.webp", "11월. 그놈이 전부 팔았다.<br>나는 그것도 기록했다."],
      ["assets/mc-38-lux-04.png", "12월. 그놈이 다시 전부 담았다.<br>이번엔 레버리지까지 썼다."],
      ["assets/situ/guy-07-gift.webp", "확신한 것이다.<br>회귀자가 확신하면 전부 건다."],
      ["assets/situ/guy-08-night.webp", "그런데 1월,<br>그놈이 산 게 무너졌다.", "next", "NEXT"],
    ],
  },
  {
    no: "15화",
    title: "미래를 모르는 첫 해",
    log: "회귀는 죽는 날에만 열린다. 그래서 그도 2026년 7월 이후는 모른다. 처음으로 공평해진 뒤에 남는 건 실력뿐이었다.",
    cuts: [
      ["assets/situ/guy-09-wed.webp", "2027년 1월.<br>그놈이 담은 종목이<br>사흘 만에 반토막 났다.", "shock", "?!"],
      ["assets/mc-38-lux-05.png", "그놈도 몰랐던 것이다."],
      ["assets/situ/guy-10-wed.webp", "당연했다.<br>왜 그 생각을 못 했을까."],
      ["assets/mc-38-lux-06.png", "우리 둘 다<br>2026년 7월에 회귀했다.", "gold", "같은 날"],
      ["assets/situ/guy-11-wed.webp", "그놈은 세 번 살았지만—<br>매번 같은 날 끝났다.", "shock", "규칙"],
      ["assets/mc-38-lux-07.png", "회귀는 죽는 날에만 열린다.<br>그놈이 나를 몰아붙인 그날,<br>그놈도 같은 날 죽었으니까.", "gold", "세계의 규칙"],
      ["assets/situ/guy-12-wed.webp", "그래서 2026년 7월 이후는<br>누구도 모른다.<br>세 번을 살아도 마찬가지다."],
      ["assets/mc-38-lux-08.png", "처음으로 공평해졌다."],
      ["assets/situ/guy-13-wed.webp", "그놈은 그날 이후<br>아무것도 못 했다."],
      ["assets/mc-38-lux-09.png", "미래 없이는<br>그냥 평범한 사람이었다.<br>아니, 평범보다 못했다."],
      ["assets/situ/guy-14-wed.webp", "28년을 미래에 기대 살았으니<br>시장을 배운 적이 없었다."],
      ["assets/mc-38-lux-10.png", "나는 달랐다."],
      ["assets/situ/guy-15-wed.webp", "나도 미래를 썼지만,<br>28년간 실제로 사고팔았다.<br>망하는 것도 여러 번 봤다."],
      ["assets/mc-26.webp", "지식이 아니라<br>실력이 남아 있었다.", "gold", "차이"],
      ["assets/situ/girl-heiress-night.webp", "2027년 3월.<br>그놈이 반대매매로 털렸다.<br>내가 2020년에 당한 것과 똑같이."],
      ["assets/car-bugatti.png", "2027년 말.<br>그놈은 파산 신청을 했다.", "win", "정산"],
      ["assets/mc-27.webp", "나는 아니었다."],
      ["assets/situ/heroine-night-6.webp", "전 여자친구는 아이를 데리러 갔다.<br>10년 만이었다.<br>그건 내가 관여할 일이 아니었다."],
      ["assets/mc-28.webp", "나는 이제<br>미래를 아는 사람이 아니다.<br>미래를 만드는 쪽이다.", "win", "완결"],
      ["assets/title-hero.png", "나 혼자만 상한가<br>지금, 다시 산다.", "next", "PLAY"],
    ],
  },
];
